import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import { createAppServer } from '../src/server.mjs';
import { execute } from '../src/application.mjs';
import { LaunchwrightClient } from '../client/index.mjs';
import { setup, baseline, candidate } from './helpers.mjs';
async function server(t){const{app,root}=setup(t);const service=createAppServer(app,{port:0,token:'synthetic-local-test-token'});const baseUrl=await service.listen();t.after(()=>service.close());const client=new LaunchwrightClient({baseUrl,token:service.token});return{app,root,service,baseUrl,client};}
function raw(port,options,body){return new Promise((resolve,reject)=>{const r=http.request({hostname:'127.0.0.1',port,...options},res=>{let b='';res.on('data',c=>b+=c);res.on('end',()=>resolve({status:res.statusCode,headers:res.headers,body:b}));});r.on('error',reject);if(body)r.write(body);r.end();});}
test('external public client creates and reads using only documented HTTP surface',async t=>{const{client}=await server(t);const description=await client.describe();assert.equal(description.native_sdk,'1.0.0');const result=await client.mutate('entity.create',{kind:'product',data:{name:'HTTP consumer'}});assert.equal((await client.get(result.entity.id)).data.name,'HTTP consumer');assert.equal((await client.inventory()).entities.length,1);});
test('unauthenticated API access is denied but login assets are available',async t=>{const{baseUrl}=await server(t);assert.equal((await fetch(baseUrl+'/api/v1/describe')).status,403);assert.equal((await fetch(baseUrl+'/')).status,200);});
test('DNS rebinding Host and cross-origin POST are denied',async t=>{const{service}=await server(t);let r=await raw(service.port,{method:'GET',path:'/api/v1/describe',headers:{Host:'untrusted.example',Authorization:'Bearer '+service.token}});assert.equal(r.status,403);r=await raw(service.port,{method:'POST',path:'/api/v1/read',headers:{Origin:'https://untrusted.example',Authorization:'Bearer '+service.token,'Content-Type':'application/json'}},'{}');assert.equal(r.status,403);});
test('query tokens, traversal and unexpected routes are not accepted',async t=>{const{baseUrl,service}=await server(t);for(const path of ['/api/v1/describe?token=synthetic','/../../.env','/api/v1/unknown']){const res=await fetch(baseUrl+path,{headers:{Authorization:'Bearer '+service.token}});assert.ok([400,404].includes(res.status));}});
test('local session creates HttpOnly SameSite cookie and cookie login works',async t=>{const{baseUrl,service}=await server(t);const res=await fetch(baseUrl+'/api/v1/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:service.token})});assert.equal(res.status,200);const cookie=res.headers.get('set-cookie');assert.ok(cookie.includes('HttpOnly'));assert.ok(cookie.includes('SameSite=Strict'));const next=await fetch(baseUrl+'/api/v1/describe',{headers:{Cookie:cookie.split(';')[0]}});assert.equal(next.status,200);});
test('wrong local token does not set a cookie',async t=>{const{baseUrl}=await server(t);const res=await fetch(baseUrl+'/api/v1/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:'wrong-synthetic-token'})});assert.equal(res.status,403);assert.equal(res.headers.get('set-cookie'),null);});
test('prepared HTTP intent can recover after caller loses original reply',async t=>{const{client,app}=await server(t);const p=await client.prepare('entity.create',{kind:'product',data:{name:'Ack lost'}});const result=await client.sendPrepared(p);assert.equal((await client.recover(p)).result.entity.id,result.entity.id);assert.equal(app.list('product').length,1);});
test('bounded bodies and malformed JSON are rejected without effects',async t=>{const{baseUrl,service,app}=await server(t);const headers={Authorization:'Bearer '+service.token,'Content-Type':'application/json'};const bad=await fetch(baseUrl+'/api/v1/prepare',{method:'POST',headers,body:'{invalid-json'});assert.equal(bad.status,400);const huge=await fetch(baseUrl+'/api/v1/prepare',{method:'POST',headers,body:JSON.stringify({payload:'a'.repeat(270000)})});assert.equal(huge.status,413);assert.equal(app.list('product').length,0);});
test('read route cannot be used as a mutation bypass',async t=>{const{client,app}=await server(t);await assert.rejects(client.read('entity.create',{kind:'product',data:{name:'Bypass'}}),{code:'InvalidArgument'});assert.equal(app.list('product').length,0);});
test('artifact downloads recheck bytes, set attachment and keep strict CSP',async t=>{const{app,baseUrl,service}=await server(t);const b=await baseline(app),{artifact}=await candidate(app,b);const r=await fetch(baseUrl+'/api/v1/artifacts/'+artifact.id+'/download',{headers:{Authorization:'Bearer '+service.token}});assert.equal(r.status,200);assert.ok(r.headers.get('content-disposition').startsWith('attachment;'));assert.ok(r.headers.get('content-security-policy').includes("default-src 'none'"));assert.ok((await r.text()).includes('Owned synthetic'));});
test('stored pending custody completes before the only outgoing invoke',async t=>{const{baseUrl,service}=await server(t);let saved=false,sends=0;const client=new LaunchwrightClient({baseUrl,token:service.token,pendingStore:{save:async()=>{saved=true;},clear:async()=>{}},fetchImpl:async(url,options)=>{if(url.endsWith('/invoke')){assert.equal(saved,true);sends++;}return fetch(url,options);}});await client.mutate('entity.create',{kind:'product',data:{name:'Stored before send'}});assert.equal(sends,1);});
test('failed pending persistence aborts before network mutation',async t=>{const{baseUrl,service,app}=await server(t);const client=new LaunchwrightClient({baseUrl,token:service.token,pendingStore:{save:async()=>{throw Error('Disk full synthetic');}}});await assert.rejects(client.mutate('entity.create',{kind:'product',data:{name:'Not sent'}}),/Disk full/);assert.equal(app.list('product').length,0);});

test('private channel bundle download is authenticated, deterministic and cache-addressed',async t=>{
  const {app,baseUrl,service,client}=await server(t),b=await baseline(app);
  const artifact=(await execute(app,'deliverable.render',{id:b.deliverable.id})).entity;
  const profile=await b.create('channel_profile',{product_id:b.product.id,name:'HTTP private bundle',channel:'private-bundle',profile_version:'1',destination_class:'private',requirements:{format:'zip'},source:'launchwright-private-bundle/1',effective_at:'2026-10-05T00:00:00.000Z',idempotency:'safe'});
  const candidate=(await execute(app,'candidate.freeze',{release_id:b.release.id,name:'HTTP bundle candidate',artifact_ids:[artifact.id],destination:'bundle',channel_profile_ids:[profile.id],contract:{version:'v2',required_reviewers:1,require_claims_verified:false}})).entity;
  const delivery=(await execute(app,'channel.package',{candidate_id:candidate.id,profile_id:profile.id,participant:'reviewer-http',locale:'en-US',allow_partial:false,omissions:[]})).entity;
  const url=client.channelBundleUrl(delivery.id);
  assert.equal((await fetch(url)).status,403);
  const first=await fetch(url,{headers:{Authorization:'Bearer '+service.token}}),second=await fetch(url,{headers:{Authorization:'Bearer '+service.token}});
  assert.equal(first.status,200);assert.equal(first.headers.get('content-type'),'application/zip');assert.ok(first.headers.get('content-disposition').includes('.zip'));
  const a=Buffer.from(await first.arrayBuffer()),c=Buffer.from(await second.arrayBuffer());
  assert.equal(a.subarray(0,4).toString('hex'),'504b0304');assert.deepEqual(a,c);assert.equal(first.headers.get('etag'),second.headers.get('etag'));
  assert.equal(first.headers.get('cache-control'),'no-store');assert.ok(first.headers.get('content-security-policy').includes("default-src 'none'"));
});
