import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import { createAppServer } from '../src/server.mjs';
import { LaunchwrightClient } from '../client/index.mjs';
import { setup, baseline, candidate } from './helpers.mjs';
async function server(t){const{app,root}=setup(t);const service=createAppServer(app,{port:0,token:'synthetic-local-test-token'});const baseUrl=await service.listen();t.after(()=>service.close());const client=new LaunchwrightClient({baseUrl,token:service.token});return{app,root,service,baseUrl,client};}
function raw(port,options,body){return new Promise((resolve,reject)=>{const r=http.request({hostname:'127.0.0.1',port,...options},res=>{let b='';res.on('data',c=>b+=c);res.on('end',()=>resolve({status:res.statusCode,headers:res.headers,body:b}));});r.on('error',reject);if(body)r.write(body);r.end();});}
test('external public client creates and reads using only documented HTTP surface',async t=>{const{client}=await server(t);const description=await client.describe();assert.equal(description.native_sdk,'0.9.0-dev.1');const result=await client.mutate('entity.create',{kind:'product',data:{name:'HTTP consumer'}});assert.equal((await client.get(result.entity.id)).data.name,'HTTP consumer');assert.equal((await client.inventory()).entities.length,1);});
test('unauthenticated API access is denied but login assets are available',async t=>{const{baseUrl}=await server(t);assert.equal((await fetch(baseUrl+'/api/v1/describe')).status,403);assert.equal((await fetch(baseUrl+'/')).status,200);});
test('DNS rebinding Host and cross-origin POST are denied',async t=>{const{service}=await server(t);let r=await raw(service.port,{method:'GET',path:'/api/v1/describe',headers:{Host:'untrusted.example',Authorization:'Bearer '+service.token}});assert.equal(r.status,403);r=await raw(service.port,{method:'POST',path:'/api/v1/read',headers:{Origin:'https://untrusted.example',Authorization:'Bearer '+service.token,'Content-Type':'application/json'}},'{}');assert.equal(r.status,403);});
test('query tokens, traversal and unexpected routes are not accepted',async t=>{const{baseUrl,service}=await server(t);for(const path of ['/api/v1/describe?token=synthetic','/../../.env','/api/v1/unknown']){const res=await fetch(baseUrl+path,{headers:{Authorization:'Bearer '+service.token}});assert.ok([400,404].includes(res.status));}});
test('local session creates HttpOnly SameSite cookie and cookie login works',async t=>{const{baseUrl,service}=await server(t);const res=await fetch(baseUrl+'/api/v1/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:service.token})});assert.equal(res.status,200);const cookie=res.headers.get('set-cookie');assert.ok(cookie.includes('HttpOnly'));assert.ok(cookie.includes('SameSite=Strict'));const next=await fetch(baseUrl+'/api/v1/describe',{headers:{Cookie:cookie.split(';')[0]}});assert.equal(next.status,200);});
test('wrong local token does not set a cookie',async t=>{const{baseUrl}=await server(t);const res=await fetch(baseUrl+'/api/v1/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:'wrong-synthetic-token'})});assert.equal(res.status,403);assert.equal(res.headers.get('set-cookie'),null);});
test('prepared HTTP intent can recover after caller loses original reply',async t=>{const{client,app}=await server(t);const p=await client.prepare('entity.create',{kind:'product',data:{name:'Ack lost'}});const result=await client.sendPrepared(p);assert.equal((await client.recover(p)).result.entity.id,result.entity.id);assert.equal(app.list('product').length,1);});
test('bounded bodies and malformed JSON are rejected without effects',async t=>{const{baseUrl,service,app}=await server(t);const headers={Authorization:'Bearer '+service.token,'Content-Type':'application/json'};const bad=await fetch(baseUrl+'/api/v1/prepare',{method:'POST',headers,body:'{invalid-json'});assert.equal(bad.status,400);const huge=await fetch(baseUrl+'/api/v1/prepare',{method:'POST',headers,body:JSON.stringify({payload:'a'.repeat(270000)})});assert.equal(huge.status,413);assert.equal(app.list('product').length,0);});
test('read route cannot be used as a mutation bypass',async t=>{const{client,app}=await server(t);await assert.rejects(client.read('entity.create',{kind:'product',data:{name:'Bypass'}}),{code:'InvalidArgument'});assert.equal(app.list('product').length,0);});
test('artifact downloads recheck bytes, set attachment and keep strict CSP',async t=>{const{app,baseUrl,service}=await server(t);const b=await baseline(app),{artifact}=await candidate(app,b);const r=await fetch(baseUrl+'/api/v1/artifacts/'+artifact.id+'/download',{headers:{Authorization:'Bearer '+service.token}});assert.equal(r.status,200);assert.ok(r.headers.get('content-disposition').startsWith('attachment;'));assert.ok(r.headers.get('content-security-policy').includes("default-src 'none'"));assert.ok((await r.text()).includes('Owned synthetic'));});
test('bundle downloads require authentication and return exact ZIP bytes',async t=>{const{app,baseUrl,service,client}=await server(t);const b=await baseline(app),{candidate:c}=await candidate(app,b);const bundle=(await client.mutate('candidate.export_bundle',{id:c.id,candidate_sha256:c.data.candidate_sha256})).entity;assert.equal((await fetch(baseUrl+'/api/v1/bundles/'+bundle.id+'/download')).status,403);const r=await fetch(baseUrl+'/api/v1/bundles/'+bundle.id+'/download',{headers:{Authorization:'Bearer '+service.token}});assert.equal(r.status,200);assert.equal(r.headers.get('content-type'),'application/zip');assert.ok(r.headers.get('content-disposition').includes('.zip'));const actual=Buffer.from(await r.arrayBuffer());assert.deepEqual(actual,app.store.readBlob(bundle.data.sha256).bytes);});
test('stored pending custody completes before the only outgoing invoke',async t=>{const{baseUrl,service}=await server(t);let saved=false,sends=0;const client=new LaunchwrightClient({baseUrl,token:service.token,pendingStore:{save:async()=>{saved=true;},clear:async()=>{}},fetchImpl:async(url,options)=>{if(url.endsWith('/invoke')){assert.equal(saved,true);sends++;}return fetch(url,options);}});await client.mutate('entity.create',{kind:'product',data:{name:'Stored before send'}});assert.equal(sends,1);});
test('failed pending persistence aborts before network mutation',async t=>{const{baseUrl,service,app}=await server(t);const client=new LaunchwrightClient({baseUrl,token:service.token,pendingStore:{save:async()=>{throw Error('Disk full synthetic');}}});await assert.rejects(client.mutate('entity.create',{kind:'product',data:{name:'Not sent'}}),/Disk full/);assert.equal(app.list('product').length,0);});
