import test from 'node:test';
import assert from 'node:assert/strict';
import { runPlatformWork } from '../src/platform.mjs';
import { execute } from '../src/application.mjs';
import { setup,baseline } from './helpers.mjs';
async function intent(app,action='graph.observe'){const b=await baseline(app);return(await execute(app,'work.prepare',{release_id:b.release.id,name:'Synthetic adapter contract',action,arguments:{project_id:'synthetic-project',idempotency_key:'synthetic-intent'},budget:{max_cost_microunits:0,currency:'USD',max_runtime_seconds:60}})).entity;}
function fake(app,{throws=false}={}){let sends=0,recoveries=0;return{get sends(){return sends;},get recoveries(){return recoveries;},async verifyIdentity(){return{synthetic:true};},async negotiate(){return{synthetic:true};},prepareRequest(action,input){return{schema_version:'synthetic-pending-test-only',action,arguments:input};},exportPending(record){return JSON.stringify(record);},async sendPrepared(){sends++;assert.equal(app.list('work')[0].data.state,'CLAIMED');if(throws)throw Error('Synthetic lost ACK');return{job_id:'synthetic-job'};},async recover(){recoveries++;return{schema_version:'semwright-platform/0.3',state:'ACCEPTED',entity_id:'synthetic-job',entity_kind:'job',accepted_revision:'1',related_references:[],safe_to_resubmit:false};}};}
test('adapter contract simulation saves exported record before one send',async t=>{const{app}=setup(t);const w=await intent(app),client=fake(app);await runPlatformWork(app,w.id,{client});assert.equal(client.sends,1);assert.equal(app.get(w.id).data.state,'RESPONSE_RECORDED');assert.equal(app.get(w.id).data.evidence_trust,'NOT_ADMITTED');});
test('adapter contract simulation preserves unknown and recovery never resends',async t=>{const{app}=setup(t);const w=await intent(app),client=fake(app,{throws:true});await assert.rejects(runPlatformWork(app,w.id,{client}),/lost ACK/);assert.equal(app.get(w.id).data.state,'OUTCOME_UNKNOWN');await assert.rejects(runPlatformWork(app,w.id,{client}),{code:'Conflict'});await runPlatformWork(app,w.id,{client,recover:true});assert.equal(client.sends,1);assert.equal(client.recoveries,1);assert.equal(app.get(w.id).data.result.recovery.safe_to_resubmit,false);});
test('recipe execution requires configured Platform budget enforcement',async t=>{const{app}=setup(t);const w=await intent(app,'recipes.execute'),client=fake(app);await assert.rejects(runPlatformWork(app,w.id,{client}),{code:'PolicyDenied'});assert.equal(client.sends,0);});
test('missing owner SDK configuration fails closed',async t=>{const{app}=setup(t);const w=await intent(app);await assert.rejects(runPlatformWork(app,w.id),{code:'Unavailable'});assert.equal(app.get(w.id).data.state,'PREPARED');});
