// SPDX-License-Identifier: AGPL-3.0-only
import { LaunchwrightClient } from '/client.mjs';
const $=s=>document.querySelector(s), root=$('#app');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const stamp=(text,kind='neutral')=>`<span class="stamp ${kind}">${esc(text)}</span>`;
const time=s=>new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(s));
let pendingStore={save:async p=>{localStorage.setItem('launchwright.pending.'+p.args.request.key,JSON.stringify(p));},clear:async key=>localStorage.removeItem('launchwright.pending.'+key)};
const api=new LaunchwrightClient({baseUrl:location.origin,pendingStore});
let model={entities:[],version:null},description=null,productId=localStorage.getItem('launchwright.product'),releaseId=localStorage.getItem('launchwright.release'),view='overview',selected=null,renderEpoch=0;
const tabs=[['overview','◫','Overview'],['targets','⊡','Targets & sources'],['scenarios','↳','Scenarios'],['claims','≡','Claims & evidence'],['deliverables','▤','Deliverables'],['impact','⌁','Impact'],['work','▷','Work'],['review','◎','Review room'],['delivery','↗','Delivery'],['templates','◇','Templates'],['history','◷','History']];
const kinds=k=>model.entities.filter(e=>e.kind===k);
const get=id=>model.entities.find(e=>e.id===id);
const inRelease=k=>kinds(k).filter(e=>e.data.release_id===releaseId);
const inProduct=k=>kinds(k).filter(e=>e.data.product_id===productId);
const button=(label,action,id='',klass='')=>`<button class="${klass}" data-action="${action}"${id?` data-id="${esc(id)}"`:''}>${esc(label)}</button>`;
const heading=(eyebrow,title,desc,actions='')=>`<div class="page-heading"><div><div class="eyebrow">${esc(eyebrow)}</div><h1>${esc(title)}</h1><p>${esc(desc)}</p></div><div class="actions">${actions}</div></div>`;
const panel=(title,body,aside='')=>`<section class="panel"><div class="panel-title"><h2>${esc(title)}</h2>${aside}</div>${body}</section>`;
const empty=(title,text,action='')=>`<div class="empty"><span class="empty-mark" aria-hidden="true">↗</span><h2>${esc(title)}</h2><p>${esc(text)}</p>${action}</div>`;
const table=(headers,rows)=>`<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th scope="col">${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>`;
const named=e=>`<strong>${esc(e.data.name)}</strong><span class="record-id">${esc(e.id)}</span>`;
const hasRelease=()=>!!get(releaseId);
let noticeTimer;
function notice(message){$('#notice').textContent=message;$('#notice').classList.add('shown');clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('#notice').classList.remove('shown'),7000);}
function setTheme(theme){document.documentElement.dataset.theme=theme;localStorage.setItem('launchwright.theme',theme);}
setTheme(localStorage.getItem('launchwright.theme')??(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'));
function route(){const u=new URL(location.href);view=tabs.some(t=>t[0]===u.hash.slice(1))?u.hash.slice(1):'overview';selected=null;render();}
window.addEventListener('hashchange',route);
async function refresh(){const result=await api.inventory();model=result;description=await api.describe();const products=kinds('product');if(!products.some(p=>p.id===productId))productId=products[0]?.id??null;const releases=inProduct('release');if(!releases.some(r=>r.id===releaseId))releaseId=releases[0]?.id??null;localStorage.setItem('launchwright.product',productId??'');localStorage.setItem('launchwright.release',releaseId??'');}
async function mutate(operation,input){const result=await api.mutate(operation,input,{expected:model.version});await refresh();return result;}
function pendingHtml(){const keys=Object.keys(localStorage).filter(k=>k.startsWith('launchwright.pending.'));if(!keys.length)return'';return`<div class="pending-panel"><strong>An intent needs reconciliation</strong><p>A saved request may have committed even without its reply. Do not create a replacement request.</p>${keys.map(key=>button('Recover saved request','recover',key,'secondary small')).join(' ')}</div>`;}
function shell(){const p=get(productId),r=get(releaseId);return`<div class="shell"><aside class="sidebar" id="sidebar"><div class="brand"><span class="brand-mark" aria-hidden="true">L</span>Launchwright</div><div><label for="product-select">Product workspace</label><select id="product-select" aria-label="Product">${kinds('product').map(e=>`<option value="${e.id}" ${e.id===productId?'selected':''}>${esc(e.data.name)}</option>`).join('')||'<option>No products yet</option>'}</select><div class="actions">${button('+ Product','new-product','','secondary small')}${button('+ Release','new-release','','secondary small')}</div></div><div><label for="release-select">Release</label><select id="release-select" aria-label="Release">${inProduct('release').map(e=>`<option value="${e.id}" ${e.id===releaseId?'selected':''}>${esc(e.data.name)}</option>`).join('')||'<option>No release selected</option>'}</select><small>${r?'Build '+esc(r.data.build):'Start with a release brief'}</small></div><nav aria-label="Workspace sections">${tabs.map(([key,icon,label])=>`<a href="#${key}" class="${view===key?'active':''}" ${view===key?'aria-current="page"':''}><span class="nav-icon" aria-hidden="true">${icon}</span>${label}</a>`).join('')}</nav><div class="side-bottom">Native SDK <strong>0.9.0-dev.1</strong><br><small>Application-local workspace<br>Platform connection not inferred</small><p><a href="/LICENSE">AGPL-3.0 license</a></p></div></aside><div class="workspace"><header class="topbar"><div class="actions">${button('☰','menu','','quiet mobile-menu')}<div class="trail">${esc(p?.data.name??'Workspace')}<span>/</span>${esc(r?.data.name??'New release')}</div></div><div class="topbar-actions"><span class="connection"><i></i>Local · persisted</span>${button('◐','theme','','quiet')}${button('Refresh','refresh','','quiet small')}</div></header><main id="main" tabindex="-1">${pendingHtml()}<div id="view-content"></div></main></div></div>`;}
async function render(){
  if(!description)return;const epoch=++renderEpoch;root.innerHTML=shell();let html;
  try{
    if(!productId){html=heading('Release production','A launch starts with a source.','Build a traceable release package. Keep editorial decisions, evidence and delivery states distinct.')+panel('Create your first workspace',empty('Nothing invented. Nothing published.','Add a product and an explicit build, then define a target and the deliverables it needs.',button('Create product','new-product')))+`<div class="callout"><strong>What works here</strong>Structured release editing, versioned text exports, input change detection, editorial review and private draft delivery. Browser capture, media rendering and external delivery require their canonical runtime integration.</div>`;}
    else if(!hasRelease()&&view!=='templates'){html=heading('Product',get(productId).data.name,'Create a release with an explicit build identity.',button('Create release','new-release'))+panel('Release brief',empty('Name the release. Pin the build.','A commercial version is not a resource revision. Launchwright keeps both.',button('Create release','new-release')));}
    else{const fn={overview,targets,scenarios,claims,deliverables,impact,work,review,delivery,templates,history}[view];html=await fn();}
    if(epoch===renderEpoch)$('#view-content').innerHTML=html;
  }catch(err){if(epoch===renderEpoch)$('#view-content').innerHTML=heading('Could not load section','The last result was not replaced.','No mutation was retried.')+panel('Request error',`<div class="panel-body"><p>${esc(err.message)}</p>${button('Refresh observation','refresh','','secondary')}</div>`);}
}
async function overview(){const r=get(releaseId),cov=await api.read('release.coverage',{release_id:releaseId});const targetCount=inRelease('target').length,outputCount=inRelease('artifact').length,reviewCount=inRelease('review').length;
  return heading('Release workspace',r.data.name,`Build ${r.data.build}. A production record, not another chat thread.`,button('Edit brief','edit',r.id,'secondary')+button('Add deliverable','new-deliverable'))+
  `<div class="summary-grid"><div><small>Registered targets</small><strong>${targetCount}</strong><span>explicit variants</span></div><div><small>Generated local artifacts</small><strong>${outputCount}</strong><span>immutable text versions</span></div><div><small>Verified claims</small><strong>${cov.pass} / ${cov.obligations}</strong><span>${cov.unknown} unknown · registered scope</span></div></div>`+
  `<div class="split">${panel('Move the release forward',`<ol class="steps"><li><span class="step-num">1</span><div><strong>Define the product context</strong><p>Build, UI language, plan, role, flags and viewport.</p></div>${button(targetCount?'Inspect':'Add target','navigate-targets','','secondary small')}</li><li><span class="step-num">2</span><div><strong>Create source-linked content</strong><p>Keep availability claims separate from screenshots and copy.</p></div>${button('Open deliverables','navigate-deliverables','','secondary small')}</li><li><span class="step-num">3</span><div><strong>Freeze and review exact bytes</strong><p>Changed inputs invalidate the candidate. A review never changes technical UNKNOWN.</p></div>${button('Review room','navigate-review','','secondary small')}</li><li><span class="step-num">4</span><div><strong>Deliver a private draft</strong><p>Alias updates use compare-and-swap. External publication stays separate.</p></div>${button('Delivery','navigate-delivery','','secondary small')}</li></ol>`)}<div>${panel('Release details',`<div class="panel-body"><dl class="fact-list"><div><dt>Build identity</dt><dd><code>${esc(r.data.build)}</code></dd></div><div><dt>Editorial status</dt><dd>${esc(r.data.status??'draft')}</dd></div><div><dt>Resource revision</dt><dd>${esc(r.version.revision)}</dd></div><div><dt>Editorial decisions</dt><dd>${reviewCount}</dd></div></dl><p class="small-note">${esc(r.data.notes??'No release notes in the brief yet.')}</p></div>`)}<div class="callout"><strong>Technical acceptance is not established</strong>The local workspace does not infer Host acceptance, canonical Graph coverage or production-ready media from an imported receipt.</div></div></div>`;
}
async function targets(){const ts=inRelease('target'),ss=inProduct('source'),builds=inProduct('build'),features=inRelease('feature'),availability=inRelease('availability');return heading('Context','Targets & sources','One target is a precise UI, audience and locale combination.',button('Add build','new-build','','secondary')+button('Add feature','new-feature','','secondary')+button('Add availability','new-availability','','secondary')+button('Add source','new-source','','secondary')+button('Add target','new-target'))+
  (ts.length?`<div class="cards">${ts.map(t=>`<section class="panel"><div class="panel-body"><div class="eyebrow">Target context</div><h2>${esc(t.data.name)}</h2><p class="muted">${esc(t.data.role)} · ${esc(t.data.plan)} · ${esc(t.data.region)}</p><div class="tags">${stamp(t.data.ui_locale)}${stamp(t.data.editorial_locale)}${stamp(`${t.data.viewport.width} × ${t.data.viewport.height}`)}</div><small>Flags</small><pre>${esc(JSON.stringify(t.data.flags,null,2))}</pre></div><footer><span class="muted">Revision ${esc(t.version.revision)}</span>${button('Edit target','edit',t.id,'secondary small')}</footer></section>`).join('')}</div>`:panel('Targets',empty('Make the context explicit.','Choose the actual UI language independently from the release copy language.',button('Add target','new-target'))))+
  `<div class="section-label"><h2>Source inventory</h2>${stamp('Declared inventory','warn')}</div>`+panel('Connected descriptions',ss.length?table(['Source','Build','Observation',''],ss.map(s=>`<tr><td>${named(s)}<div class="sub">${esc(s.data.type)} · ${esc(s.data.locator)}</div></td><td><code>${esc(s.data.build)}</code></td><td>${stamp(s.data.coverage,'warn')}<div class="sub">No connection or capture implied</div></td><td>${button('Edit','edit',s.id,'secondary small')}</td></tr>`)):empty('Declare an authorized source.','URLs and commands are stored as descriptions. Launchwright does not silently navigate or execute them.'))+
  panel('Build snapshots',builds.length?table(['Snapshot','Version / source','Digest',''],builds.map(b=>'<tr><td>'+named(b)+'</td><td>'+esc(b.data.version_label??'Unlabeled')+'<div class="sub">'+esc(b.data.source_revision??'No source revision')+'</div></td><td><code>'+esc(b.data.artifact_digest.slice(0,20))+'…</code></td><td>'+button('Edit','edit',b.id,'secondary small')+'</td></tr>')):empty('No structured build snapshot yet.','A release label is not proof of the deployed build.'))+
  panel('Feature availability',features.length?table(['Feature','Lifecycle','Target-specific rules',''],features.map(f=>{const rules=availability.filter(a=>a.data.feature_id===f.id);return '<tr><td>'+named(f)+'</td><td>'+stamp(f.data.status)+'</td><td>'+(rules.length?rules.map(a=>esc(get(a.data.target_id)?.data.name)+' · '+stamp(a.data.state,a.data.state==='unavailable'?'bad':'warn')+' '+button('Edit','edit',a.id,'secondary small')).join('<br>'):'No target rule')+'</td><td>'+button('Edit feature','edit',f.id,'secondary small')+'</td></tr>';})):empty('No features registered.','Model feature state separately from pixels and release copy.'));
}
async function scenarios(){const ss=inRelease('scenario'),anchors=inRelease('anchor');return heading('Capture planning','Scenarios','Reusable steps and exact anchors. A declared recipe is not an executed scenario.',button('Add anchor','new-anchor','','secondary')+button('Add scenario','new-scenario'))+panel('Scenario inventory',ss.length?table(['Scenario','Source / target','State',''],ss.map(s=>`<tr><td>${named(s)}<div class="sub">${s.data.steps.length} steps · ${s.data.anchors.length} anchors</div></td><td>${esc(get(s.data.source_id)?.data.name)}<div class="sub">${esc(get(s.data.target_id)?.data.name)}</div></td><td>${stamp('Needs native validation','warn')}</td><td>${button('Edit','edit',s.id,'secondary small')}</td></tr>`)):empty('Describe a flow worth showing.','Capture execution must be admitted through a supported Semwright driver and Platform recipe.',button('Create scenario','new-scenario')))+`<div class="callout"><strong>Readiness is checked, not assumed</strong>Login pages, loaders, ambiguous anchors and a wrong build cannot become valid capture evidence merely because a screenshot exists.</div>`+
  panel('State anchors',anchors.length?table(['Anchor','Source / target','Resolution',''],anchors.map(a=>'<tr><td>'+named(a)+'</td><td>'+esc(get(a.data.source_id)?.data.name)+'<div class="sub">'+esc(get(a.data.target_id)?.data.name)+'</div></td><td>'+esc(a.data.strategy)+' · exactly '+esc(a.data.expected_count)+'<div class="sub">'+esc(a.data.value)+'</div></td><td>'+button('Edit','edit',a.id,'secondary small')+'</td></tr>')):empty('No reusable anchors.','Anchors are resources with explicit cardinality; ambiguity fails closed.',button('Add anchor','new-anchor')));}
async function claims(){const cs=inRelease('claim'),es=inRelease('evidence'),blocks=inRelease('copy_block'),contracts=inRelease('release_contract');const cov=await api.read('release.coverage',{release_id:releaseId});return heading('Trust & provenance','Claims & evidence','Technical, editorial and rights decisions have different owners.',button('Add ReleaseContract','new-release_contract','','secondary')+button('Add CopyBlock','new-copy_block','','secondary')+button('Import provenance','new-evidence','','secondary')+button('Add claim','new-claim'))+
  panel('Claims',cs.length?table(['Claim','Context','Verification',''],cs.map(c=>`<tr><td>${named(c)}<div class="sub">${esc(c.data.text)}</div></td><td>${esc(get(c.data.target_id)?.data.name)}<div class="sub">${esc(c.data.category)}</div></td><td>${stamp('UNKNOWN','warn')}<div class="sub">${c.data.evidence_ids.length} evidence references</div></td><td>${button('Edit','edit',c.id,'secondary small')}</td></tr>`)):empty('Write a bounded claim.','“Available to everyone” needs plan and role evidence. Pixels alone are insufficient.',button('Add claim','new-claim')))+
  panel('Imported provenance',es.length?table(['Evidence','Build / rights','Admission'],es.map(e=>`<tr><td>${named(e)}<div class="sub">${esc(e.data.description)}</div></td><td>${esc(e.data.build)}<div class="sub">${esc(e.data.rights)} — declaration</div></td><td>${stamp('Imported declaration','warn')}<div class="sub">Technical UNKNOWN · ${esc(e.data.classification)}</div></td></tr>`)):empty('No evidence has been imported.','Imported metadata is retained as an assertion, never promoted to canonical native evidence.'))+
  panel('Copy blocks',blocks.length?table(['Copy','Claim / locale','Owner',''],blocks.map(b=>'<tr><td>'+named(b)+'<div class="sub">'+esc(b.data.content)+'</div></td><td>'+esc(get(b.data.claim_id)?.data.name)+'<div class="sub">'+esc(b.data.locale)+'</div></td><td>'+stamp(b.data.owner)+'</td><td>'+button('Edit','edit',b.id,'secondary small')+'</td></tr>')):empty('No CopyBlocks yet.','Copy can be reformulated while the linked Claim keeps the product meaning.'))+
  panel('Release contracts',contracts.length?table(['Contract','Required obligations','Ready / blocked',''],contracts.map(c=>{const state=cov.contracts.find(x=>x.id===c.id);return '<tr><td>'+named(c)+'</td><td>'+esc(state?.total??0)+'</td><td>'+esc(state?.ready??0)+' ready · '+esc(state?.failed??0)+' failed · '+esc(state?.unknown??0)+' unknown</td><td>'+button('Edit','edit',c.id,'secondary small')+'</td></tr>';})):empty('No ReleaseContract yet.','Define the real denominator for readiness instead of a vanity percentage.'))+
  `<p class="small-note">${cov.obligations} registered claims. ${cov.unknown} remain unknown. Content outside the inventory is not covered.</p>`;
}
async function deliverables(){const ds=inRelease('deliverable'),as=inRelease('artifact');let preview='';if(selected){const a=get(selected);if(a?.kind==='artifact'){const data=await api.read('artifact.read',{id:a.id});preview=panel(a.data.name,`<pre class="preview">${esc(data.text)}</pre>`,`<a href="${api.artifactUrl(a.id)}" download>Download ${esc(a.data.extension.toUpperCase())}</a>`);}}
  return heading('Editorial production','Deliverables','Versioned outputs with exact source pins. Existing artifacts are never overwritten.',button('Add deliverable','new-deliverable'))+
  panel('Editable documents',ds.length?table(['Document','Target / format','Sources',''],ds.map(d=>`<tr><td>${named(d)}</td><td>${esc(get(d.data.target_id)?.data.name)}<div class="sub">${esc(d.data.format.toUpperCase())}</div></td><td>${d.data.source_ids.length} sources · ${d.data.claim_ids.length} claims</td><td><div class="actions">${button('Edit','edit',d.id,'secondary small')}${button('Render text','render',d.id,'small')}</div></td></tr>`)):empty('Start with the release story.','Markdown, safe HTML, structured JSON, email drafts and timed VTT cues are available locally.',button('Create deliverable','new-deliverable')))+
  panel('Immutable output versions',as.length?table(['Output','Bytes','Integrity',''],as.map(a=>`<tr><td>${named(a)}<div class="sub">${time(a.created)}</div></td><td>${a.data.size_bytes} B<div class="sub">${esc(a.data.extension)}</div></td><td><code>${esc(a.data.sha256.slice(0,20))}…</code><div class="sub">Editorial draft · no product execution implied</div></td><td>${button('Preview','preview',a.id,'secondary small')}</td></tr>`)):empty('The first render will appear here.','Rendering saves an immutable artifact plus its input revisions.'))+preview;
}
async function impact(){const data=await api.read('release.impact',{release_id:releaseId});const bs=inRelease('binding'),proposals=inRelease('impact_proposal');return heading('Change control','Impact inbox','Compare registered input revisions without pretending to own canonical Project Graph state.',button('Plan impact','plan-impact','','secondary')+button('Add surface binding','new-binding','','secondary'))+
  `<div class="callout"><strong>Coverage: declared dependencies only</strong>An unobserved dependency remains unknown. An unchanged registered input does not prove independence from everything else.</div>`+
  panel('Artifacts with changed inputs',data.items.length?table(['Artifact','Changed resources','Next action'],data.items.map(i=>`<tr><td>${esc(get(i.artifact_id)?.data.name)}<span class="record-id">${esc(i.artifact_id)}</span></td><td>${i.changed.map(c=>`${esc(get(c.id)?.data.name??c.id)} · ${esc(c.reason)}`).join('<br>')}</td><td>${button('Render new version','render',i.deliverable_id,'secondary small')}</td></tr>`)):empty('No registered input changes found.','This is not a complete-product CURRENT verdict. Canonical Graph coverage remains unobserved.'))+
  panel('Surface bindings',bs.length?table(['Surface','Policy','Pinned artifact',''],bs.map(b=>`<tr><td>${named(b)}</td><td>${stamp(b.data.mode)}<div class="sub">${b.data.mode==='rolling'?'Revalidate changed inputs':'Preserve historical output'}</div></td><td><code>${esc(b.data.pinned_artifact_id??'Rolling selection')}</code></td><td>${button('Edit','edit',b.id,'secondary small')}</td></tr>`)):empty('Keep LTS and rolling surfaces distinct.','A new release does not silently rewrite historical documentation.'))+
  panel('Release-contract blockers',data.contract_blockers.length?table(['Contract','Obligation','State / reason'],data.contract_blockers.map(o=>'<tr><td>'+esc(get(o.contract_id)?.data.name??o.contract_id)+'</td><td>'+esc(o.kind)+' · '+esc(get(o.id)?.data.name??o.id)+'</td><td>'+stamp(o.state,o.state==='FAIL'?'bad':'warn')+'<div class="sub">'+esc((o.reasons??[]).join(', '))+'</div></td></tr>')):empty('No contract blockers in the registered inventory.','Unknown dependencies outside the inventory still remain unknown.'))+
  panel('Saved impact proposals',proposals.length?table(['Proposal','Causes','Authority'],proposals.map(p=>'<tr><td>'+named(p)+'<div class="sub">'+time(p.created)+'</div></td><td>'+esc(p.data.cause_ids.length)+' registered causes</td><td>'+stamp('NO EXECUTION AUTHORITY','warn')+'<div class="sub">0 jobs created</div></td></tr>')):empty('No proposal saved.','Opening Impact never creates jobs. Save a proposal only when you want a durable planning record.'));
}
async function work(){const ws=inRelease('work');return heading('Execution','Work','Durable intent records point to Platform; they do not create a second scheduler.',button('Prepare Platform intent','new-work','','secondary'))+
  `<div class="callout"><strong>Platform is not connected by this browser session</strong>Use the pinned SDK adapter and owner configuration to negotiate actions. Preparation does not execute, spend or publish anything.</div>`+
  panel('Intent journal',ws.length?table(['Intent','Action','State','Job'],ws.map(w=>`<tr><td>${named(w)}</td><td><code>${esc(w.data.action)}</code></td><td>${stamp(w.data.state,w.data.state==='OUTCOME_UNKNOWN'?'bad':'warn')}<div class="sub">Budget enforcement: ${w.data.budget_enforced?'reported':'Platform required'}</div></td><td><code>${esc(w.data.platform_job_id??'Not observed')}</code></td></tr>`)):empty('No execution intent has been prepared.','Long-running work belongs to Platform and its workers. A lost reply is reconciled, not automatically resent.'));
}
async function review(){const cs=inRelease('candidate');let details='';if(selected){const c=get(selected);if(c?.kind==='candidate'){const data=await api.read('candidate.inspect',{id:c.id});details=panel(c.data.name,data.gates.map(g=>`<details class="review-gate"><summary>${stamp(g.state,g.state==='PASS'?'good':g.state==='FAIL'?'bad':'warn')}<strong>${esc(g.name)}</strong></summary><pre>${esc(JSON.stringify(g.details,null,2))}</pre></details>`).join('')+`<div class="panel-body"><p><code>${esc(c.data.candidate_sha256)}</code></p><div class="actions">${button('Record editorial decision','review-decision',c.id,'secondary')}${button('Record private draft','deliver',c.id)}</div><p class="small-note">${data.reviews.length} editorial decisions. External publication is unavailable. Technical UNKNOWN cannot be waived into PASS.</p></div>`);}}
  return heading('Exact-candidate review','Review room','Freeze artifact bytes, input versions, destination and contract before a decision.',button('Freeze candidate','freeze'))+
  panel('Candidates',cs.length?table(['Candidate','Digest','Frozen',''],cs.map(c=>`<tr><td>${named(c)}</td><td><code>${esc(c.data.candidate_sha256.slice(0,24))}…</code></td><td>${time(c.created)}<div class="sub">${c.data.manifest.artifact_ids.length} artifacts</div></td><td>${button('Inspect gates','inspect',c.id,'secondary small')}</td></tr>`)):empty('Review a specific version, not a moving page.','Render at least one deliverable, then freeze the exact inputs and bytes.',button('Freeze candidate','freeze')))+details;
}
async function delivery(){const ds=inRelease('delivery');return heading('Distribution','Delivery board','Private draft receipts and alias history. No social post, email or public launch is sent from this workspace.')+
  panel('Private delivery receipts',ds.length?table(['Destination','Candidate','Local state','External state'],ds.map(d=>`<tr><td>${named(d)}<div class="sub">Alias revision ${esc(d.data.alias_version.revision)}</div></td><td><code>${esc(d.data.candidate_sha256.slice(0,22))}…</code></td><td>${stamp('Private draft','warn')}<div class="sub">${time(d.created)}</div></td><td>${stamp('NOT SENT')}<div class="sub">Technical ${esc(d.data.technical_state)}</div></td></tr>`)):empty('Nothing has been delivered.','A reviewed candidate can create an immutable private-draft receipt. Publication to an external channel requires a separate authorized integration.',button('Open review room','navigate-review','','secondary')));
}
async function templates(){const ts=inProduct('template');return heading('Reusable authoring','Templates','Allowlisted text parameters, versioned definitions and explicit target selection.',button('Create template','new-template'))+
  panel('Local templates',ts.length?table(['Template','Format','Parameters',''],ts.map(t=>`<tr><td>${named(t)}</td><td>${esc(t.data.format)}</td><td>${t.data.parameters.map(p=>`<code>${esc(p)}</code>`).join(', ')}</td><td><div class="actions">${button('Edit','edit',t.id,'secondary small')}${button('Instantiate','instantiate',t.id,'small')}</div></td></tr>`)):empty('Reusable content without hidden authority.','Local instantiation does not publish a Platform template or share data across accounts.',button('Create template','new-template')));
}
async function history(){const data=await api.read('events.list',{after:0,limit:128});return heading('Audit trail','History','Committed application mutations. Sequence and request binding survive restarts.')+
  panel('Recent registered events',data.items.length?`<ol class="history">${data.items.toReversed().map(e=>`<li><code>#${e.seq}</code><div><strong>${esc(e.operation)}</strong><p>${esc(e.principal)} · workspace revision ${esc(e.revision)}</p><code class="record-id">${esc(e.payload.request_key)}</code></div><time datetime="${esc(e.occurred)}">${time(e.occurred)}</time></li>`).join('')}</ol>`:empty('No committed mutations yet.','Read-only navigation and preparation do not create audit entries.'))+`<p class="small-note">Showing ${data.items.length} entries from sequence 1. ${data.complete?'Complete at watermark '+data.watermark:'More entries exist; the public API supports cursor pagination.'}</p>`;
}
// Accessible schema-driven forms; complex scenario structures are explicit JSON, never executable code.
const selectField=(key,label,items,value)=>({key,label,type:'select',items:items.map(e=>typeof e==='string'?{value:e,label:e}:{value:e.id,label:e.data.name}),value});
const jsonField=(key,label,value,help='JSON only; no executable expressions.')=>({key,label,type:'json',value,help});
const textField=(key,label,value='',type='text',help='')=>({key,label,type,value,help});
const entityFields=(kind,data={})=>{
 const r=get(releaseId),ts=inRelease('target'),sources=inProduct('source'),builds=inProduct('build'),features=inRelease('feature'),availabilities=inRelease('availability'),claims=inRelease('claim'),deliverables=inRelease('deliverable');
 const fields={
 product:[textField('name','Product name',data.name??''),textField('description','Description',data.description??'','textarea')],
 build:[textField('name','Build snapshot name',data.name??''),textField('artifact_digest','Artifact SHA-256',data.artifact_digest??''),textField('version_label','Commercial version label',data.version_label??''),textField('source_revision','Source revision',data.source_revision??''),textField('observed_at','Observed at (ISO)',data.observed_at??''),textField('notes','Build notes',data.notes??'','textarea')],
 release:[textField('name','Release name',data.name??''),textField('build','Build identity label',data.build??'','text','Keep this distinct from the commercial release name.'),selectField('build_id','Pinned build snapshot',[{id:'',data:{name:'No structured snapshot'}},...builds],data.build_id??''),selectField('status','Editorial status',['draft','active','lts','archived'],data.status??'draft'),textField('notes','Brief',data.notes??'','textarea')],
 source:[textField('name','Source name',data.name??''),selectField('type','Source type',['web','cli','mobile-import','godot','document'],data.type??'web'),textField('locator','Locator',data.locator??'','text','Stored as a description. External origins require an approved purpose before navigation.'),textField('purpose','Approved purpose',data.purpose??'','textarea'),selectField('approval','Source approval',['pending','approved','denied'],data.approval??'pending'),textField('build','Build',data.build??r?.data.build??''),selectField('build_id','Structured build snapshot',[{id:'',data:{name:'No structured snapshot'}},...builds],data.build_id??''),selectField('coverage','Observation coverage',['declared','partial','unknown'],data.coverage??'declared'),textField('observed_at','Observation time (ISO)',data.observed_at??'')],
 target:[textField('name','Target name',data.name??''),textField('ui_locale','UI locale',data.ui_locale??'en-US'),textField('editorial_locale','Copy locale',data.editorial_locale??'en-US'),textField('audio_locale','Audio locale',data.audio_locale??'en-US'),textField('role','Product role',data.role??'viewer'),textField('plan','Product plan',data.plan??'basic'),textField('region','Region',data.region??'global'),jsonField('flags','Feature flags',data.flags??{}),jsonField('viewport','Viewport',data.viewport??{width:1440,height:900,scale_milli:1000},'Scale is an integer in thousandths so request digests stay exact.')],
 feature:[textField('name','Feature name',data.name??''),textField('key','Stable feature key',data.key??''),selectField('status','Declared lifecycle',['active','beta','disabled','deprecated'],data.status??'active'),textField('description','Feature description',data.description??'','textarea')],
 availability:[textField('name','Availability rule',data.name??''),selectField('feature_id','Feature',features,data.feature_id),selectField('target_id','Target',ts,data.target_id),selectField('state','Declared availability',['ga','beta','unavailable','unknown'],data.state??'unknown'),selectField('basis','Basis',['declared','imported','observed'],data.basis??'declared'),textField('valid_from','Valid from (ISO)',data.valid_from??''),textField('valid_until','Valid until (ISO)',data.valid_until??'')],
 anchor:[textField('name','Anchor name',data.name??''),selectField('source_id','Source',sources,data.source_id),selectField('target_id','Target',ts,data.target_id),selectField('strategy','Resolution strategy',['aria','text','testid','cli-match','semantic'],data.strategy??'aria'),textField('value','Anchor value',data.value??''),jsonField('expected_count','Expected unique count',data.expected_count??1,'Exactly 1 is required; ambiguity fails closed.')],
 scenario:[textField('name','Scenario name',data.name??''),selectField('source_id','Source',sources,data.source_id),selectField('target_id','Target',ts,data.target_id),textField('version_label','Scenario version',data.version_label??''),selectField('reset_strategy','Reset strategy',['none','fixture-reset','isolated-context','operator-reset'],data.reset_strategy??'none'),jsonField('effects','Declared effects',data.effects??[],'Declarations only; they do not grant effect authority.'),jsonField('steps','Steps',data.steps??[{action:'assert',anchor:'heading'}]),jsonField('anchors','Legacy inline anchors',data.anchors??[{name:'heading',role:'heading',label:'Example product screen',expected_count:1}]),selectField('readiness','Readiness',['declared','needs-validation'],data.readiness??'needs-validation')],
 claim:[textField('name','Claim label',data.name??''),textField('text','Exact claim meaning',data.text??'','textarea'),selectField('target_id','Target',ts,data.target_id),selectField('category','Category',['feature','availability','price','instruction','editorial'],data.category??'feature'),textField('subject','Subject',data.subject??''),textField('scope','Scope',data.scope??''),textField('owner','Owner',data.owner??''),selectField('availability_id','Availability rule',[{id:'',data:{name:'No availability rule'}},...availabilities],data.availability_id??''),textField('unit','Unit',data.unit??''),textField('currency','Currency',data.currency??''),textField('valid_from','Valid from (ISO)',data.valid_from??''),textField('valid_until','Valid until (ISO)',data.valid_until??''),jsonField('evidence_ids','Evidence IDs',data.evidence_ids??[],'Imported evidence cannot manufacture canonical PASS.')],
 copy_block:[textField('name','Copy block name',data.name??''),selectField('target_id','Target',ts,data.target_id),selectField('claim_id','Claim',claims,data.claim_id),textField('locale','Locale',data.locale??'en-US'),selectField('owner','Copy owner',['human','managed'],data.owner??'human'),textField('content','Copy text',data.content??'','textarea')],
 release_contract:[textField('name','Contract name',data.name??''),jsonField('required_claim_ids','Required claim IDs',data.required_claim_ids??claims.map(c=>c.id)),jsonField('optional_claim_ids','Optional claim IDs',data.optional_claim_ids??[]),jsonField('required_deliverable_ids','Required deliverable IDs',data.required_deliverable_ids??deliverables.map(d=>d.id))],
 deliverable:[textField('name','Document name',data.name??''),selectField('target_id','Target',ts,data.target_id),selectField('format','Output format',['markdown','html','json','email','vtt'],data.format??'markdown'),textField('content','Content',data.content??'','textarea'),jsonField('claim_ids','Claim IDs',data.claim_ids??[]),jsonField('copy_block_ids','CopyBlock IDs',data.copy_block_ids??[],'Link copy to structured claims so meaning changes invalidate outputs.'),jsonField('source_ids','Source IDs',data.source_ids??[]),jsonField('captions','Caption cues (VTT only)',data.captions??[],'Objects: start_ms, end_ms, text. Non-overlapping times; media alignment is unverified.')],
 binding:[textField('name','Surface name',data.name??''),selectField('mode','Binding policy',['rolling','pinned','lts'],data.mode??'rolling'),selectField('deliverable_id','Deliverable',inRelease('deliverable'),data.deliverable_id),selectField('pinned_artifact_id','Pinned artifact (required for LTS / pinned)',[{id:'',data:{name:'No fixed artifact'}},...inRelease('artifact')],data.pinned_artifact_id??'')],
 template:[textField('name','Template name',data.name??''),selectField('format','Format',['markdown','html','json','email'],data.format??'markdown'),textField('content','Template text',data.content??'# {{title}}\n\n{{summary}}','textarea'),jsonField('parameters','Allowed parameter names',data.parameters??['title','summary'])]
 };return fields[kind];
};
function openForm(title,fields,onSubmit,submit='Save'){
 const dialog=$('#editor');$('#editor-title').textContent=title;$('#save-editor').textContent=submit;$('#form-error').textContent='';
 $('#editor-fields').innerHTML=fields.map(f=>`<div class="field"><label for="f-${f.key}">${esc(f.label)}</label>${f.type==='select'?`<select id="f-${f.key}" name="${f.key}">${f.items.map(i=>`<option value="${esc(i.value)}"${String(f.value??'')===String(i.value)?' selected':''}>${esc(i.label)}</option>`).join('')}</select>`:f.type==='checkbox'?`<input id="f-${f.key}" name="${f.key}" type="checkbox"${f.value?' checked':''}>`:f.type==='textarea'||f.type==='json'?`<textarea id="f-${f.key}" name="${f.key}" rows="${f.type==='json'?5:8}">${esc(f.type==='json'?JSON.stringify(f.value,null,2):f.value)}</textarea>`:`<input id="f-${f.key}" name="${f.key}" type="${f.type==='password'?'password':'text'}" value="${esc(f.value)}" autocomplete="off">`}${f.help?`<small>${esc(f.help)}</small>`:''}</div>`).join('');
 $('#editor-form').onsubmit=async event=>{event.preventDefault();const save=$('#save-editor');save.disabled=true;$('#form-error').textContent='';try{const data={};for(const f of fields){const el=$(`#f-${f.key}`);data[f.key]=f.type==='json'?JSON.parse(el.value):f.type==='checkbox'?el.checked:el.value;}await onSubmit(data);dialog.close();await render();notice('Saved to the application journal.');}catch(err){$('#form-error').textContent=err.message;}finally{save.disabled=false;}};
 dialog.showModal();
}
$('#close-editor').onclick=$('#cancel-editor').onclick=()=>$('#editor').close();
function editEntity(kind,e){
 if(!['product','build','release','source','feature','release_contract','template'].includes(kind)&&!inRelease('target').length&&kind!=='target'){notice('Add a target context first.');return;}
 openForm(e?`Edit ${kind}`:`Create ${kind}`,entityFields(kind,e?.data),async data=>{
   if(['build','release','source','template'].includes(kind))data.product_id=e?.data.product_id??productId;
   if(['target','feature','availability','anchor','scenario','claim','copy_block','release_contract','deliverable','binding'].includes(kind))data.release_id=e?.data.release_id??releaseId;
   for(const key of ['build_id','availability_id','pinned_artifact_id','valid_from','valid_until','observed_at','purpose'])if(data[key]==='')delete data[key];
   if(kind==='binding'&&!data.pinned_artifact_id)delete data.pinned_artifact_id;
   const result=await mutate(e?'entity.update':'entity.create',e?{id:e.id,expected:e.version,data}:{kind,data});
   if(kind==='product'){productId=result.entity.id;releaseId=null;}if(kind==='release')releaseId=result.entity.id;
   localStorage.setItem('launchwright.product',productId??'');localStorage.setItem('launchwright.release',releaseId??'');
 });
}
root.addEventListener('change',async event=>{try{if(event.target.id==='product-select'){productId=event.target.value;releaseId=null;await refresh();render();}if(event.target.id==='release-select'){releaseId=event.target.value;localStorage.setItem('launchwright.release',releaseId);selected=null;render();}}catch(err){notice(err.message);}});
root.addEventListener('click',async event=>{
 const el=event.target.closest('[data-action]');if(!el)return;const action=el.dataset.action,id=el.dataset.id;
 try{
  if(action.startsWith('navigate-')){location.hash=action.slice(9);return;}
  if(action==='menu'){$('#sidebar').classList.toggle('mobile-open');return;}
  if(action==='theme'){setTheme(document.documentElement.dataset.theme==='dark'?'light':'dark');return;}
  if(action==='refresh'){await refresh();await render();return;}
  if(action==='plan-impact'){
   const data=await api.read('release.impact',{release_id:releaseId});const causeIds=[...new Set(data.items.flatMap(i=>i.changed.map(c=>c.id)))];
   openForm('Save impact proposal',[jsonField('cause_ids','Cause resource IDs',causeIds,'A proposal records causes and scope but creates no jobs or authority.'),textField('note','Planning note','','textarea')],async d=>mutate('impact.plan',{release_id:releaseId,...d}),'Save proposal');return;
  }
  if(action==='recover'){const p=JSON.parse(localStorage.getItem(id));const r=await api.recover(p);if(r.state==='recorded'){await pendingStore.clear(p.args.request.key);await refresh();await render();notice('The original committed result was recovered.');}else notice(`Recovery state: ${r.state}. The original intent remains saved and was not resent.`);return;}
  if(action==='edit'){const e=get(id);editEntity(e.kind,e);return;}
  if(action.startsWith('new-')&&!['new-evidence','new-work'].includes(action)){const kind=action.slice(4);if(kind==='release'&&!productId){notice('Create a product first.');return;}editEntity(kind);return;}
  if(action==='render'){el.disabled=true;await mutate('deliverable.render',{id});await render();notice('Created immutable text artifact and source pins.');return;}
  if(action==='preview'||action==='inspect'){selected=id;await render();return;}
  if(action==='new-evidence'){
   openForm('Import provenance declaration',[textField('name','Evidence name'),selectField('target_id','Target',inRelease('target')),selectField('source_id','Source',inProduct('source')),textField('build','Observed build',get(releaseId).data.build),selectField('classification','Source classification',['actual','demo','sanitized','editorial','generated','imported'],'imported'),selectField('rights','Rights declaration',['owned','licensed','unknown','restricted'],'unknown'),textField('origin_digest','Original content SHA-256'),textField('description','What was observed and what was not','','textarea')],async d=>mutate('evidence.import',{...d,release_id:releaseId}),'Import as unverified');return;
  }
  if(action==='freeze'){
   openForm('Freeze a release candidate',[textField('name','Candidate name',get(releaseId).data.name+' — review'),jsonField('artifact_ids','Exact artifact IDs',inRelease('artifact').map(a=>a.id),'Remove superseded versions. Every selected artifact must still match its source pins.'),textField('destination','Private alias','release-draft'),jsonField('contract','Local review contract',{version:'editorial-v1',required_reviewers:1,require_claims_verified:true})],async d=>mutate('candidate.freeze',{...d,release_id:releaseId}),'Freeze exact candidate');return;
  }
  if(action==='review-decision'){const c=get(id);openForm('Editorial decision',[selectField('decision','Decision',['approve-editorial','request-changes','reject'],'request-changes'),textField('comment','Reason or requested change','','textarea')],async d=>mutate('candidate.review',{...d,id,candidate_sha256:c.data.candidate_sha256}),'Record decision');return;}
  if(action==='deliver'){const c=get(id);const prior=inRelease('delivery').filter(d=>d.data.name===c.data.manifest.destination).sort((a,b)=>Number(BigInt(a.data.alias_version.revision)-BigInt(b.data.alias_version.revision))).at(-1);openForm('Record private draft',[textField('destination','Destination (read-only binding)',c.data.manifest.destination),{key:'acknowledge_draft',label:'I understand: this records a private draft, not a verified or external publication.',type:'checkbox',value:false}],async d=>{if(d.destination!==c.data.manifest.destination)throw Error('Destination is frozen in the candidate.');return mutate('candidate.deliver_private',{id,candidate_sha256:c.data.candidate_sha256,alias_expected:prior?.data.alias_version??null,acknowledge_draft:d.acknowledge_draft});},'Record private draft');return;}
  if(action==='instantiate'){const t=get(id);openForm('Instantiate template',[textField('name','Deliverable name',t.data.name),selectField('target_id','Target',inRelease('target')),jsonField('parameters','Parameter values',Object.fromEntries(t.data.parameters.map(p=>[p,''])))],async d=>mutate('template.instantiate',{...d,id,release_id:releaseId}),'Create deliverable');return;}
  if(action==='new-work'){openForm('Prepare a Platform intent',[textField('name','Intent label'),selectField('action','Canonical action',['recipes.prepare','recipes.execute','jobs.get','graph.observe','graph.observation','evidence.get','artifacts.get'],'recipes.prepare'),jsonField('arguments','Canonical action input',{},'Use the actual negotiated Platform action schema. No new endpoint is inferred.'),jsonField('budget','Budget proposal',{max_cost_microunits:0,currency:'USD',max_runtime_seconds:60})],async d=>mutate('work.prepare',{...d,release_id:releaseId}),'Save intent only');return;}
 }catch(err){notice(err.message);await render();}finally{el.disabled=false;}
});
function login(error=''){
 root.innerHTML=`<main class="login" id="main"><div class="brand"><span class="brand-mark" aria-hidden="true">L</span>Launchwright</div><div class="eyebrow">Local release workspace</div><h1>Your launch.<br>Your source of truth.</h1><p>Unlock the workspace running on this computer. No account is created and no data is published.</p><form id="login-form"><label for="token">Local session token</label><input id="token" name="token" type="password" autocomplete="off" required><button type="submit">Open workspace</button><p id="login-error" role="alert">${esc(error)}</p></form><p class="small-note">The launcher prints the token file path. Open it locally; never put the token in a URL, source file or release package.</p><p class="small-note">AGPL-3.0-only · <a href="/LICENSE">License</a></p></main>`;
 $('#login-form').onsubmit=async e=>{e.preventDefault();try{await api.request('/api/v1/session',{token:$('#token').value});$('#token').value='';await refresh();route();}catch(err){$('#login-error').textContent=err.message;}};
}
try{await refresh();route();}catch(err){login(err.code==='PermissionDenied'?'':err.message);}
