// SPDX-License-Identifier: AGPL-3.0-only
import { LaunchwrightClient } from '/client.mjs';
const $=s=>document.querySelector(s), root=$('#app');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const stamp=(text,kind='neutral')=>`<span class="stamp ${kind}">${esc(text)}</span>`;
const time=s=>new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(s));
let pendingStore={save:async p=>{localStorage.setItem('launchwright.pending.'+p.args.request.key,JSON.stringify(p));},clear:async key=>localStorage.removeItem('launchwright.pending.'+key)};
const api=new LaunchwrightClient({baseUrl:location.origin,pendingStore});
let model={entities:[],version:null},description=null,productId=localStorage.getItem('launchwright.product'),releaseId=localStorage.getItem('launchwright.release'),view='overview',selected=null,renderEpoch=0;
const tabs=[['overview','◫','Overview'],['targets','⊡','Targets & sources'],['scenarios','↳','Scenarios'],['claims','≡','Claims & evidence'],['deliverables','▤','Deliverables'],['documents','¶','Documents'],['localization','文','Localization'],['impact','⌁','Impact'],['work','▷','Work'],['review','◎','Review room'],['delivery','↗','Delivery'],['templates','◇','Templates'],['extensions','⊞','Extensions'],['history','◷','History']];
const kinds=k=>model.entities.filter(e=>e.kind===k);
const get=id=>model.entities.find(e=>e.id===id);
const inRelease=k=>kinds(k).filter(e=>e.data.release_id===releaseId);
const inProduct=k=>kinds(k).filter(e=>e.data.product_id===productId);
const button=(label,action,id='',klass='')=>`<button class="${klass}" data-action="${action}"${id?` data-id="${esc(id)}"`:''}>${esc(label)}</button>`;
const heading=(eyebrow,title,desc,actions='')=>`<div class="page-heading"><div><div class="eyebrow">${esc(eyebrow)}</div><h1>${esc(title)}</h1><p>${esc(desc)}</p></div><div class="actions">${actions}</div></div>`;
const panel=(title,body,aside='')=>`<section class="panel"><div class="panel-title"><h2>${esc(title)}</h2>${aside}</div>${body}</section>`;
const empty=(title,text,action='')=>`<div class="empty"><span class="empty-mark" aria-hidden="true">↗</span><h2>${esc(title)}</h2><p>${esc(text)}</p>${action}</div>`;
const table=(headers,rows)=>`<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th scope="col">${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>`;
const named=e=>`<strong>${esc(e.data.name)}</strong><span class="record-id">${esc(e.id)}</span>`;
const hasRelease=()=>!!get(releaseId);
let noticeTimer;
function notice(message){$('#notice').textContent=message;$('#notice').classList.add('shown');clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('#notice').classList.remove('shown'),7000);}
function setTheme(theme){document.documentElement.dataset.theme=theme;localStorage.setItem('launchwright.theme',theme);}
setTheme(localStorage.getItem('launchwright.theme')??(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'));
function route(){const u=new URL(location.href);view=tabs.some(t=>t[0]===u.hash.slice(1))?u.hash.slice(1):'overview';selected=null;render();}
window.addEventListener('hashchange',route);
async function refresh(){const result=await api.inventory();model=result;description=await api.describe();const products=kinds('product');if(!products.some(p=>p.id===productId))productId=products[0]?.id??null;const releases=inProduct('release');if(!releases.some(r=>r.id===releaseId))releaseId=releases[0]?.id??null;localStorage.setItem('launchwright.product',productId??'');localStorage.setItem('launchwright.release',releaseId??'');}
async function mutate(operation,input){const result=await api.mutate(operation,input,{expected:model.version});await refresh();return result;}
function pendingHtml(){const keys=Object.keys(localStorage).filter(k=>k.startsWith('launchwright.pending.'));if(!keys.length)return'';return`<div class="pending-panel"><strong>An intent needs reconciliation</strong><p>A saved request may have committed even without its reply. Do not create a replacement request.</p>${keys.map(key=>button('Recover saved request','recover',key,'secondary small')).join(' ')}</div>`;}
function shell(){const p=get(productId),r=get(releaseId);return`<div class="shell"><aside class="sidebar" id="sidebar"><div class="brand"><span class="brand-mark" aria-hidden="true">L</span>Launchwright</div><div><label for="product-select">Product workspace</label><select id="product-select" aria-label="Product">${kinds('product').map(e=>`<option value="${e.id}" ${e.id===productId?'selected':''}>${esc(e.data.name)}</option>`).join('')||'<option>No products yet</option>'}</select><div class="actions">${button('+ Product','new-product','','secondary small')}${button('+ Release','new-release','','secondary small')}</div></div><div><label for="release-select">Release</label><select id="release-select" aria-label="Release">${inProduct('release').map(e=>`<option value="${e.id}" ${e.id===releaseId?'selected':''}>${esc(e.data.name)}</option>`).join('')||'<option>No release selected</option>'}</select><small>${r?'Build '+esc(r.data.build):'Start with a release brief'}</small></div><nav aria-label="Workspace sections">${tabs.map(([key,icon,label])=>`<a href="#${key}" class="${view===key?'active':''}" ${view===key?'aria-current="page"':''}><span class="nav-icon" aria-hidden="true">${icon}</span>${label}</a>`).join('')}</nav><div class="side-bottom">Native SDK <strong>0.9.0-dev.1</strong><br><small>Application-local workspace<br>Platform connection not inferred</small><p><a href="/LICENSE">AGPL-3.0 license</a></p></div></aside><div class="workspace"><header class="topbar"><div class="actions">${button('☰','menu','','quiet mobile-menu')}<div class="trail">${esc(p?.data.name??'Workspace')}<span>/</span>${esc(r?.data.name??'New release')}</div></div><div class="topbar-actions"><span class="connection"><i></i>Local · persisted</span>${button('◐','theme','','quiet')}${button('Refresh','refresh','','quiet small')}</div></header><main id="main" tabindex="-1">${pendingHtml()}<div id="view-content"></div></main></div></div>`;}
async function render(){
  if(!description)return;const epoch=++renderEpoch;root.innerHTML=shell();let html;
  try{
    if(!productId){html=heading('Release production','A launch starts with a source.','Build a traceable release package. Keep editorial decisions, evidence and delivery states distinct.')+panel('Create your first workspace',empty('Nothing invented. Nothing published.','Add a product and an explicit build, then define a target and the deliverables it needs.',button('Create product','new-product')))+`<div class="callout"><strong>What works here</strong>Structured release editing, versioned text exports, input change detection, editorial review and private draft delivery. Browser capture, media rendering and external delivery require their canonical runtime integration.</div>`;}
    else if(!hasRelease()&&view!=='templates'){html=heading('Product',get(productId).data.name,'Create a release with an explicit build identity.',button('Create release','new-release'))+panel('Release brief',empty('Name the release. Pin the build.','A commercial version is not a resource revision. Launchwright keeps both.',button('Create release','new-release')));}
    else{const fn={overview,targets,scenarios,claims,deliverables,documents,localization,impact,work,review,delivery,templates,extensions,history}[view];html=await fn();}
    if(epoch===renderEpoch)$('#view-content').innerHTML=html;
  }catch(err){if(epoch===renderEpoch)$('#view-content').innerHTML=heading('Could not load section','The last result was not replaced.','No mutation was retried.')+panel('Request error',`<div class="panel-body"><p>${esc(err.message)}</p>${button('Refresh observation','refresh','','secondary')}</div>`);}
}
async function overview(){const r=get(releaseId),cov=await api.read('release.coverage',{release_id:releaseId});const targetCount=inRelease('target').length,outputCount=inRelease('artifact').length,reviewCount=inRelease('review').length;
  return heading('Release workspace',r.data.name,`Build ${r.data.build}. A production record, not another chat thread.`,button('Edit brief','edit',r.id,'secondary')+button('Add deliverable','new-deliverable'))+
  `<div class="summary-grid"><div><small>Registered targets</small><strong>${targetCount}</strong><span>explicit variants</span></div><div><small>Generated local artifacts</small><strong>${outputCount}</strong><span>immutable text versions</span></div><div><small>Verified claims</small><strong>${cov.pass} / ${cov.obligations}</strong><span>${cov.unknown} unknown · registered scope</span></div></div>`+
  `<div class="split">${panel('Move the release forward',`<ol class="steps"><li><span class="step-num">1</span><div><strong>Define the product context</strong><p>Build, UI language, plan, role, flags and viewport.</p></div>${button(targetCount?'Inspect':'Add target','navigate-targets','','secondary small')}</li><li><span class="step-num">2</span><div><strong>Create source-linked content</strong><p>Keep availability claims separate from screenshots and copy.</p></div>${button('Open deliverables','navigate-deliverables','','secondary small')}</li><li><span class="step-num">3</span><div><strong>Freeze and review exact bytes</strong><p>Changed inputs invalidate the candidate. A review never changes technical UNKNOWN.</p></div>${button('Review room','navigate-review','','secondary small')}</li><li><span class="step-num">4</span><div><strong>Deliver a private draft</strong><p>Alias updates use compare-and-swap. External publication stays separate.</p></div>${button('Delivery','navigate-delivery','','secondary small')}</li></ol>`)}<div>${panel('Release details',`<div class="panel-body"><dl class="fact-list"><div><dt>Build identity</dt><dd><code>${esc(r.data.build)}</code></dd></div><div><dt>Editorial status</dt><dd>${esc(r.data.status??'draft')}</dd></div><div><dt>Resource revision</dt><dd>${esc(r.version.revision)}</dd></div><div><dt>Editorial decisions</dt><dd>${reviewCount}</dd></div></dl><p class="small-note">${esc(r.data.notes??'No release notes in the brief yet.')}</p></div>`)}<div class="callout"><strong>Technical acceptance is not established</strong>The local workspace does not infer Host acceptance, canonical Graph coverage or production-ready media from an imported receipt.</div></div></div>`;
}
async function targets(){const ts=inRelease('target'),ss=inProduct('source'),builds=inProduct('build'),features=inRelease('feature'),availability=inRelease('availability');return heading('Context','Targets & sources','One target is a precise UI, audience and locale combination.',button('Add build','new-build','','secondary')+button('Add feature','new-feature','','secondary')+button('Add availability','new-availability','','secondary')+button('Add source','new-source','','secondary')+button('Add target','new-target'))+
  (ts.length?`<div class="cards">${ts.map(t=>`<section class="panel"><div class="panel-body"><div class="eyebrow">Target context</div><h2>${esc(t.data.name)}</h2><p class="muted">${esc(t.data.role)} · ${esc(t.data.plan)} · ${esc(t.data.region)}</p><div class="tags">${stamp(t.data.ui_locale)}${stamp(t.data.editorial_locale)}${stamp(`${t.data.viewport.width} × ${t.data.viewport.height}`)}</div><small>Flags</small><pre>${esc(JSON.stringify(t.data.flags,null,2))}</pre></div><footer><span class="muted">Revision ${esc(t.version.revision)}</span>${button('Edit target','edit',t.id,'secondary small')}</footer></section>`).join('')}</div>`:panel('Targets',empty('Make the context explicit.','Choose the actual UI language independently from the release copy language.',button('Add target','new-target'))))+
  `<div class="section-label"><h2>Source inventory</h2>${stamp('Declared inventory','warn')}</div>`+panel('Connected descriptions',ss.length?table(['Source','Build','Observation',''],ss.map(s=>`<tr><td>${named(s)}<div class="sub">${esc(s.data.type)} · ${esc(s.data.locator)}</div></td><td><code>${esc(s.data.build)}</code></td><td>${stamp(s.data.coverage,'warn')}<div class="sub">No connection or capture implied</div></td><td>${button('Edit','edit',s.id,'secondary small')}</td></tr>`)):empty('Declare an authorized source.','URLs and commands are stored as descriptions. Launchwright does not silently navigate or execute them.'))+
  panel('Build snapshots',builds.length?table(['Snapshot','Version / source','Digest',''],builds.map(b=>'<tr><td>'+named(b)+'</td><td>'+esc(b.data.version_label??'Unlabeled')+'<div class="sub">'+esc(b.data.source_revision??'No source revision')+'</div></td><td><code>'+esc(b.data.artifact_digest.slice(0,20))+'…</code></td><td>'+button('Edit','edit',b.id,'secondary small')+'</td></tr>')):empty('No structured build snapshot yet.','A release label is not proof of the deployed build.'))+
  panel('Feature availability',features.length?table(['Feature','Lifecycle','Target-specific rules',''],features.map(f=>{const rules=availability.filter(a=>a.data.feature_id===f.id);return '<tr><td>'+named(f)+'</td><td>'+stamp(f.data.status)+'</td><td>'+(rules.length?rules.map(a=>esc(get(a.data.target_id)?.data.name)+' · '+stamp(a.data.state,a.data.state==='unavailable'?'bad':'warn')+' '+button('Edit','edit',a.id,'secondary small')).join('<br>'):'No target rule')+'</td><td>'+button('Edit feature','edit',f.id,'secondary small')+'</td></tr>';})):empty('No features registered.','Model feature state separately from pixels and release copy.'));
}
async function scenarios(){const ss=inRelease('scenario'),anchors=inRelease('anchor');return heading('Capture planning','Scenarios','Reusable steps and exact anchors. A declared recipe is not an executed scenario.',button('Add anchor','new-anchor','','secondary')+button('Add scenario','new-scenario'))+panel('Scenario inventory',ss.length?table(['Scenario','Source / target','State',''],ss.map(s=>`<tr><td>${named(s)}<div class="sub">${s.data.steps.length} steps · ${s.data.anchors.length} anchors</div></td><td>${esc(get(s.data.source_id)?.data.name)}<div class="sub">${esc(get(s.data.target_id)?.data.name)}</div></td><td>${stamp('Needs native validation','warn')}</td><td>${button('Edit','edit',s.id,'secondary small')}</td></tr>`)):empty('Describe a flow worth showing.','Capture execution must be admitted through a supported Semwright driver and Platform recipe.',button('Create scenario','new-scenario')))+`<div class="callout"><strong>Readiness is checked, not assumed</strong>Login pages, loaders, ambiguous anchors and a wrong build cannot become valid capture evidence merely because a screenshot exists.</div>`+
  panel('State anchors',anchors.length?table(['Anchor','Source / target','Resolution',''],anchors.map(a=>'<tr><td>'+named(a)+'</td><td>'+esc(get(a.data.source_id)?.data.name)+'<div class="sub">'+esc(get(a.data.target_id)?.data.name)+'</div></td><td>'+esc(a.data.strategy)+' · exactly '+esc(a.data.expected_count)+'<div class="sub">'+esc(a.data.value)+'</div></td><td>'+button('Edit','edit',a.id,'secondary small')+'</td></tr>')):empty('No reusable anchors.','Anchors are resources with explicit cardinality; ambiguity fails closed.',button('Add anchor','new-anchor')));}
async function claims(){const cs=inRelease('claim'),es=inRelease('evidence'),blocks=inRelease('copy_block'),contracts=inRelease('release_contract');const cov=await api.read('release.coverage',{release_id:releaseId});return heading('Trust & provenance','Claims & evidence','Technical, editorial and rights decisions have different owners.',button('Add ReleaseContract','new-release_contract','','secondary')+button('Add CopyBlock','new-copy_block','','secondary')+button('Import provenance','new-evidence','','secondary')+button('Add claim','new-claim'))+
  panel('Claims',cs.length?table(['Claim','Context','Verification',''],cs.map(c=>`<tr><td>${named(c)}<div class="sub">${esc(c.data.text)}</div></td><td>${esc(get(c.data.target_id)?.data.name)}<div class="sub">${esc(c.data.category)}</div></td><td>${stamp('UNKNOWN','warn')}<div class="sub">${c.data.evidence_ids.length} evidence references</div></td><td>${button('Edit','edit',c.id,'secondary small')}</td></tr>`)):empty('Write a bounded claim.','“Available to everyone” needs plan and role evidence. Pixels alone are insufficient.',button('Add claim','new-claim')))+
  panel('Imported provenance',es.length?table(['Evidence','Build / rights','Admission'],es.map(e=>`<tr><td>${named(e)}<div class="sub">${esc(e.data.description)}</div></td><td>${esc(e.data.build)}<div class="sub">${esc(e.data.rights)} — declaration</div></td><td>${stamp('Imported declaration','warn')}<div class="sub">Technical UNKNOWN · ${esc(e.data.classification)}</div></td></tr>`)):empty('No evidence has been imported.','Imported metadata is retained as an assertion, never promoted to canonical native evidence.'))+
  panel('Copy blocks',blocks.length?table(['Copy','Claim / locale','Owner',''],blocks.map(b=>'<tr><td>'+named(b)+'<div class="sub">'+esc(b.data.content)+'</div></td><td>'+esc(get(b.data.claim_id)?.data.name)+'<div class="sub">'+esc(b.data.locale)+'</div></td><td>'+stamp(b.data.owner)+'</td><td>'+button('Edit','edit',b.id,'secondary small')+'</td></tr>')):empty('No CopyBlocks yet.','Copy can be reformulated while the linked Claim keeps the product meaning.'))+
  panel('Release contracts',contracts.length?table(['Contract','Required obligations','Ready / blocked',''],contracts.map(c=>{const state=cov.contracts.find(x=>x.id===c.id);return '<tr><td>'+named(c)+'</td><td>'+esc(state?.total??0)+'</td><td>'+esc(state?.ready??0)+' ready · '+esc(state?.failed??0)+' failed · '+esc(state?.unknown??0)+' unknown</td><td>'+button('Edit','edit',c.id,'secondary small')+'</td></tr>';})):empty('No ReleaseContract yet.','Define the real denominator for readiness instead of a vanity percentage.'))+
  `<p class="small-note">${cov.obligations} registered claims. ${cov.unknown} remain unknown. Content outside the inventory is not covered.</p>`;
}
async function deliverables(){const ds=inRelease('deliverable'),as=inRelease('artifact');let preview='';if(selected){const a=get(selected);if(a?.kind==='artifact'){const data=await api.read('artifact.read',{id:a.id});preview=panel(a.data.name,`<pre class="preview">${esc(data.text)}</pre>`,`<a href="${api.artifactUrl(a.id)}" download>Download ${esc(a.data.extension.toUpperCase())}</a>`);}}
  return heading('Editorial production','Deliverables','Versioned outputs with exact source pins. Existing artifacts are never overwritten.',button('Add deliverable','new-deliverable'))+
  panel('Editable documents',ds.length?table(['Document','Target / format','Sources',''],ds.map(d=>`<tr><td>${named(d)}</td><td>${esc(get(d.data.target_id)?.data.name)}<div class="sub">${esc(d.data.format.toUpperCase())}</div></td><td>${d.data.source_ids.length} sources · ${d.data.claim_ids.length} claims</td><td><div class="actions">${button('Edit','edit',d.id,'secondary small')}${button('Render text','render',d.id,'small')}</div></td></tr>`)):empty('Start with the release story.','Markdown, safe HTML, structured JSON, email drafts and timed VTT cues are available locally.',button('Create deliverable','new-deliverable')))+
  panel('Immutable output versions',as.length?table(['Output','Bytes','Integrity',''],as.map(a=>`<tr><td>${named(a)}<div class="sub">${time(a.created)}</div></td><td>${a.data.size_bytes} B<div class="sub">${esc(a.data.extension)}</div></td><td><code>${esc(a.data.sha256.slice(0,20))}…</code><div class="sub">Editorial draft · no product execution implied</div></td><td>${button('Preview','preview',a.id,'secondary small')}</td></tr>`)):empty('The first render will appear here.','Rendering saves an immutable artifact plus its input revisions.'))+preview;
}
async function documents(){
  const ds=inRelease('document'),ps=inRelease('proposal');let detail='';
  if(selected){const d=get(selected);if(d?.kind==='document'){const info=await api.read('document.inspect',{id:d.id});detail=panel('Document structure',`<div class="panel-body"><div class="summary-line"><strong>${esc(d.data.name)}</strong>${stamp(d.data.branch_mode)}</div><p>${d.data.sections.length} sections · ${d.data.sections.reduce((n,s)=>n+s.blocks.length,0)} blocks · human overwrite: never.</p><pre>${esc(JSON.stringify(info.open_proposals.map(p=>({id:p.id,state:p.data.state,stale:p.stale})),null,2))}</pre></div>`);}}
  return heading('Structured authoring','Documents','Human and managed blocks keep separate ownership. Managed changes are proposals against an exact base.',button('Create document','new-document'))+
  panel('Versioned documents',ds.length?table(['Document','Branch / locale','Ownership',''],ds.map(d=>{const human=d.data.sections.flatMap(s=>s.blocks).filter(b=>b.owner==='human').length,managed=d.data.sections.flatMap(s=>s.blocks).filter(b=>b.owner==='managed').length;return`<tr><td>${named(d)}<div class="sub">${esc(d.data.external_base?.locator??'Local document')}</div></td><td>${stamp(d.data.branch_mode)}<div class="sub">${esc(d.data.locale)} · ${esc(d.data.format)}</div></td><td>${human} human · ${managed} managed</td><td><div class="actions">${button('Inspect','inspect',d.id,'secondary small')}${human?button('Edit human block','edit-document-human',d.id,'secondary small'):''}${managed?button('Propose change','propose-document',d.id,'secondary small'):''}${button('Render','render-document',d.id,'small')}</div></td></tr>`; })):empty('No structured document yet.','Start with explicit human and managed areas; imported code remains text unless a separate sandboxed verifier runs it.',button('Create document','new-document')))+
  panel('Managed proposals',ps.length?table(['Proposal','Base','State',''],ps.map(p=>`<tr><td>${named(p)}<div class="sub">${esc(p.data.reason||'No rationale')}</div></td><td>document rev ${esc(p.data.document_version.revision)}<div class="sub">${esc(p.data.external_base?.revision??'local base')}</div></td><td>${stamp(p.data.state,p.data.state==='APPLIED'?'good':p.data.state==='OPEN'?'warn':'neutral')}</td><td>${p.data.state==='OPEN'?button('Resolve','resolve-proposal',p.id,'secondary small'):''}</td></tr>`)):empty('No pending managed changes.','A Git/docs base conflict blocks apply instead of overwriting upstream work.'))+detail;
}
async function localization(){
  const gs=inProduct('glossary'),fs=inProduct('font_profile'),ts=inRelease('translation');let detail='';
  if(selected){const tr=get(selected);if(tr?.kind==='translation'){const info=await api.read('translation.inspect',{id:tr.id});detail=panel('Translation inspection',`<div class="panel-body"><div class="summary-line"><strong>${esc(tr.data.name)}</strong>${stamp(info.computed_state,info.computed_state==='REVIEWED_FOR_TARGET'?'good':info.computed_state==='BLOCKED'?'bad':'warn')}</div><p>${esc(tr.data.target_locale)} · semantic verification: ${esc(info.semantic_verification)}</p><p>Human text is preserved across stale inputs. Automatic fallback: never.</p><pre>${esc(JSON.stringify({changed:info.changed,blocked:info.blocked,risk:info.risk},null,2))}</pre></div>`);}}
  return heading('Locale production','Localization','Source, target, glossary and font policy are pinned independently. A fluent string is never an automatic semantic PASS.',button('Create translation','new-translation')+button('Add glossary','new-glossary','','secondary')+button('Add font policy','new-font_profile','','secondary'))+
  panel('Translations',ts.length?table(['Translation','Locale / source','State',''],ts.map(tr=>`<tr><td>${named(tr)}<div class="sub">${esc(tr.data.text.slice(0,110))}</div></td><td>${esc(tr.data.target_locale)}<div class="sub">${esc(get(tr.data.source_id)?.data.name??tr.data.source_id)}</div></td><td>${stamp(tr.data.state,tr.data.state==='REVIEWED_FOR_TARGET'?'good':'warn')}<div class="sub">${esc(tr.data.semantic_verification)}</div></td><td><div class="actions">${button('Inspect','inspect',tr.id,'secondary small')}${button('Edit text','edit-translation',tr.id,'secondary small')}${button('Rebase pins','rebase-translation',tr.id,'secondary small')}${button('Review','review-translation',tr.id,'secondary small')}${button('Render','render-translation',tr.id,'small')}</div></td></tr>`)):empty('No translation record yet.','Create one from a CopyBlock, deliverable or structured document after defining glossary and font policy.',button('Create translation','new-translation')))+
  panel('Glossaries',gs.length?table(['Glossary','Locales','Terms',''],gs.map(g=>`<tr><td>${named(g)}</td><td>${esc(g.data.source_locale)} → ${esc(g.data.target_locale)}</td><td>${g.data.terms.length}<div class="sub">fallback: ${esc(g.data.fallback_policy)}</div></td><td>${button('Edit','edit',g.id,'secondary small')}</td></tr>`)):empty('No glossary.','A glossary revision makes dependent translations stale without deleting human edits.'))+
  panel('Font policies',fs.length?table(['Policy','Locales','Rights',''],fs.map(f=>`<tr><td>${named(f)}<div class="sub">${esc(f.data.font_family_ref)}</div></td><td>${esc(f.data.locales.join(', '))}<div class="sub">coverage: ${esc(f.data.coverage)}</div></td><td>${stamp(f.data.rights)}<div class="sub">binary embedded: no</div></td><td>${button('Edit','edit',f.id,'secondary small')}</td></tr>`)):empty('No font policy.','Reference coverage and rights; Launchwright does not copy font binaries from the authoring machine.'))+detail;
}
async function impact(){const data=await api.read('release.impact',{release_id:releaseId});const bs=inRelease('binding'),proposals=inRelease('impact_proposal');return heading('Change control','Impact inbox','Compare registered input revisions without pretending to own canonical Project Graph state.',button('Plan impact','plan-impact','','secondary')+button('Add surface binding','new-binding','','secondary'))+
  `<div class="callout"><strong>Coverage: declared dependencies only</strong>An unobserved dependency remains unknown. An unchanged registered input does not prove independence from everything else.</div>`+
  panel('Artifacts with changed inputs',data.items.length?table(['Artifact','Changed resources','Next action'],data.items.map(i=>`<tr><td>${esc(get(i.artifact_id)?.data.name)}<span class="record-id">${esc(i.artifact_id)}</span></td><td>${i.changed.map(c=>`${esc(get(c.id)?.data.name??c.id)} · ${esc(c.reason)}`).join('<br>')}</td><td>${button('Render new version','render',i.deliverable_id,'secondary small')}</td></tr>`)):empty('No registered input changes found.','This is not a complete-product CURRENT verdict. Canonical Graph coverage remains unobserved.'))+
  panel('Surface bindings',bs.length?table(['Surface','Policy','Pinned artifact',''],bs.map(b=>`<tr><td>${named(b)}</td><td>${stamp(b.data.mode)}<div class="sub">${b.data.mode==='rolling'?'Revalidate changed inputs':'Preserve historical output'}</div></td><td><code>${esc(b.data.pinned_artifact_id??'Rolling selection')}</code></td><td>${button('Edit','edit',b.id,'secondary small')}</td></tr>`)):empty('Keep LTS and rolling surfaces distinct.','A new release does not silently rewrite historical documentation.'))+
  panel('Release-contract blockers',data.contract_blockers.length?table(['Contract','Obligation','State / reason'],data.contract_blockers.map(o=>'<tr><td>'+esc(get(o.contract_id)?.data.name??o.contract_id)+'</td><td>'+esc(o.kind)+' · '+esc(get(o.id)?.data.name??o.id)+'</td><td>'+stamp(o.state,o.state==='FAIL'?'bad':'warn')+'<div class="sub">'+esc((o.reasons??[]).join(', '))+'</div></td></tr>')):empty('No contract blockers in the registered inventory.','Unknown dependencies outside the inventory still remain unknown.'))+
  panel('Saved impact proposals',proposals.length?table(['Proposal','Causes','Authority'],proposals.map(p=>'<tr><td>'+named(p)+'<div class="sub">'+time(p.created)+'</div></td><td>'+esc(p.data.cause_ids.length)+' registered causes</td><td>'+stamp('NO EXECUTION AUTHORITY','warn')+'<div class="sub">0 jobs created</div></td></tr>')):empty('No proposal saved.','Opening Impact never creates jobs. Save a proposal only when you want a durable planning record.'));
}
async function work(){const ws=inRelease('work');return heading('Execution','Work','Durable intent records point to Platform; they do not create a second scheduler.',button('Prepare Platform intent','new-work','','secondary'))+
  `<div class="callout"><strong>Platform is not connected by this browser session</strong>Use the pinned SDK adapter and owner configuration to negotiate actions. Preparation does not execute, spend or publish anything.</div>`+
  panel('Intent journal',ws.length?table(['Intent','Action','State','Job'],ws.map(w=>`<tr><td>${named(w)}</td><td><code>${esc(w.data.action)}</code></td><td>${stamp(w.data.state,w.data.state==='OUTCOME_UNKNOWN'?'bad':'warn')}<div class="sub">Budget enforcement: ${w.data.budget_enforced?'reported':'Platform required'}</div></td><td><code>${esc(w.data.platform_job_id??'Not observed')}</code></td></tr>`)):empty('No execution intent has been prepared.','Long-running work belongs to Platform and its workers. A lost reply is reconciled, not automatically resent.'));
}
async function review(){const cs=inRelease('candidate');let details='';if(selected){const c=get(selected);if(c?.kind==='candidate'){const data=await api.read('candidate.inspect',{id:c.id});const dimensions=Object.entries(data.review_dimensions).map(([name,d])=>`<div class="summary-line"><strong>${esc(name)}</strong>${stamp(d.state,d.state==='APPROVED'?'good':d.state==='CHANGES_REQUESTED'?'bad':'warn')}<span>${d.approvals} approvals${d.required?' · required':' · optional'}</span></div>`).join('');details=panel(c.data.name,data.gates.map(g=>`<details class="review-gate"><summary>${stamp(g.state,g.state==='PASS'?'good':g.state==='FAIL'?'bad':'warn')}<strong>${esc(g.name)}</strong></summary><pre>${esc(JSON.stringify(g.details,null,2))}</pre></details>`).join('')+`<div class="panel-body"><p><code>${esc(c.data.candidate_sha256)}</code></p><div class="review-dimensions">${dimensions}</div><div class="actions">${button('Record review decision','review-decision',c.id,'secondary')}${button('Export exact ZIP','export-bundle',c.id,'secondary')}${button('Record private draft','deliver',c.id)}</div><p class="small-note">${data.reviews.length} decisions across independent dimensions. Review readiness: ${data.review_ready?'approved':'pending'}. Technical UNKNOWN is never promoted by editorial or waiver.</p></div>`);}}
  return heading('Exact-candidate review','Review room','Freeze bytes, channel profiles, input versions, destination and review contract before a decision.',button('Freeze candidate','freeze'))+
  panel('Candidates',cs.length?table(['Candidate','Digest','Frozen',''],cs.map(c=>`<tr><td>${named(c)}<div class="sub">${(c.data.manifest.channel_profile_ids??[]).length} channel profiles</div></td><td><code>${esc(c.data.candidate_sha256.slice(0,24))}…</code></td><td>${time(c.created)}<div class="sub">${c.data.manifest.artifact_ids.length} artifacts</div></td><td>${button('Inspect gates','inspect',c.id,'secondary small')}</td></tr>`)):empty('Review a specific version, not a moving page.','Render at least one deliverable, then freeze the exact inputs, channel profiles and bytes.',button('Freeze candidate','freeze')))+details;
}
async function delivery(){
  const ds=inRelease('delivery'),bundles=inRelease('bundle'),profiles=inProduct('channel_profile'),channel=await api.read('release.channels',{release_id:releaseId});
  let detail='';if(selected){const attempt=get(selected);if(attempt?.kind==='channel_attempt'){const inspected=await api.read('channel.inspect',{id:attempt.id});detail=panel('Attempt inspection',`<div class="panel-body"><div class="summary-line"><strong>${esc(attempt.data.name)}</strong>${stamp(attempt.data.state,attempt.data.state==='OBSERVED_PUBLISHED'?'good':attempt.data.state==='FAILED'?'bad':'warn')}</div><p>Candidate/current: ${inspected.candidate_version_current?'yes':'no'} · profile/current: ${inspected.channel_profile_version_current?'yes':'no'} · compatible: ${inspected.compatibility.ready?'yes':'no'}.</p><p class="small-note">Pending custody: ${esc(inspected.pending.state??'none')} · automatic resend: never · reconcile required: ${inspected.reconcile_required?'yes':'no'}.</p><pre>${esc(JSON.stringify(inspected.compatibility.issues,null,2))}</pre></div>`);}}
  return heading('Distribution','Delivery board','Export, private delivery and external channel state are separate. A 2xx or lost acknowledgement never becomes “published” by inference.',button('Prepare channel attempt','prepare-channel','','secondary')+button('Add channel profile','new-channel_profile','','secondary'))+
  panel('Channel profiles',profiles.length?table(['Profile','Mode','Formats / locales','Recovery'],profiles.map(p=>`<tr><td>${named(p)}<div class="sub">${esc(p.data.channel)} · profile ${esc(p.data.profile_version)}</div></td><td>${stamp(p.data.delivery_mode,p.data.delivery_mode==='publish'?'warn':'neutral')}<div class="sub">withdrawal: ${esc(p.data.withdrawal)}</div></td><td>${esc(p.data.formats.join(', '))}<div class="sub">${esc(p.data.locales.join(', '))}</div></td><td>${esc(p.data.idempotency)}<div class="actions">${button('Edit','edit',p.id,'secondary small')}</div></td></tr>`)):empty('No channel profile is pinned yet.','Version destinations, formats, locales, idempotency and withdrawal policy before freezing a candidate.',button('Add channel profile','new-channel_profile')))+
  panel('Channel participants',channel.attempts.length?table(['Attempt','Pinned destination','State',''],channel.attempts.map(a=>{const p=get(a.data.channel_profile_id);const actions=button('Inspect','inspect-channel',a.id,'secondary small')+(['SENT','PROCESSING','UNKNOWN'].includes(a.data.state)?button('Record reconciliation','reconcile-channel',a.id,'secondary small'):'')+(a.data.retry_allowed?button('Prepare retry','retry-channel',a.id,'secondary small'):'')+(a.data.state!=='PREPARED'?button('Withdrawal plan','withdraw-channel',a.id,'secondary small'):'');return`<tr><td>${named(a)}<div class="sub">logical ${esc(a.data.logical_key)} · attempt ${esc(a.data.attempt_no)}</div></td><td>${esc(p?.data.name??a.data.channel_profile_id)}<div class="sub">${esc(a.data.channel_policy.channel)} · ${esc(a.data.channel_policy.delivery_mode)}</div></td><td>${stamp(a.data.state,a.data.state==='OBSERVED_PUBLISHED'?'good':a.data.state==='FAILED'?'bad':'warn')}<div class="sub">dispatch ${esc(a.data.dispatch_state)} · resend ${a.data.resent?'yes':'no'}</div></td><td><div class="actions">${actions}</div></td></tr>`; })):empty('No external channel intent has been prepared.','Preparation pins candidate/profile/version and a logical request. The browser does not perform the external send.',button('Prepare channel attempt','prepare-channel')),`<span class="small-note">Atomic across channels: no · participants are independent</span>`)+detail+
  panel('Withdrawal plans',channel.withdrawals.length?table(['Plan','Scope','Capability','External action'],channel.withdrawals.map(w=>`<tr><td>${named(w)}<div class="sub">${esc(w.data.reason)}</div></td><td>${esc(w.data.scope)}</td><td>${esc(w.data.channel_capability)}</td><td>${stamp('PLAN ONLY','warn')}<div class="sub">all copies removed: no</div></td></tr>`)):empty('No withdrawal plan has been recorded.','A plan cannot claim downstream caches or copies were removed without complete evidence.'))+
  panel('Exported candidate bundles',bundles.length?table(['Bundle','Candidate','State',''],bundles.map(b=>`<tr><td>${named(b)}<div class="sub"><code>${esc(b.data.sha256.slice(0,22))}…</code> · ${esc(b.data.size_bytes)} bytes</div></td><td><code>${esc(b.data.candidate_sha256.slice(0,22))}…</code></td><td>${stamp('EXPORTED','good')}<div class="sub">Not delivered externally</div></td><td>${button('Download ZIP','download-bundle',b.id,'secondary small')}</td></tr>`)):empty('No exact bundle exported.','Export creates deterministic ZIP bytes from the frozen candidate without recording an external delivery.',button('Open review room','navigate-review','','secondary')))+
  panel('Private delivery receipts',ds.length?table(['Destination','Candidate','Local state','External state'],ds.map(d=>`<tr><td>${named(d)}<div class="sub">Alias revision ${esc(d.data.alias_version.revision)}</div></td><td><code>${esc(d.data.candidate_sha256.slice(0,22))}…</code></td><td>${stamp('Private draft','warn')}<div class="sub">${time(d.created)}</div></td><td>${stamp('NOT SENT')}<div class="sub">Technical ${esc(d.data.technical_state)}</div></td></tr>`)):empty('Nothing has been privately delivered.','A reviewed candidate can create an immutable private-draft receipt. Publication to an external channel requires a separate authorized integration.',button('Open review room','navigate-review','','secondary')));
}
async function templates(){const ts=inProduct('template');return heading('Reusable authoring','Templates','Allowlisted text parameters, versioned definitions and explicit target selection.',button('Create template','new-template'))+
  panel('Local templates',ts.length?table(['Template','Format','Parameters',''],ts.map(t=>`<tr><td>${named(t)}</td><td>${esc(t.data.format)}</td><td>${t.data.parameters.map(p=>`<code>${esc(p)}</code>`).join(', ')}</td><td><div class="actions">${button('Edit','edit',t.id,'secondary small')}${button('Instantiate','instantiate',t.id,'small')}</div></td></tr>`)):empty('Reusable content without hidden authority.','Local instantiation does not publish a Platform template or share data across accounts.',button('Create template','new-template')));
}
async function extensions(){
  const xs=kinds('extension_contract');let detail='';
  if(selected){const e=get(selected);if(e?.kind==='extension_contract'){const info=await api.read('extension.describe',{id:e.id});detail=panel('Generic extension view',`<div class="panel-body"><div class="summary-line"><strong>${esc(e.data.name)}</strong>${stamp(e.data.state,e.data.state==='ACTIVE'?'good':'warn')}</div><p>${esc(e.data.type)} · contract ${esc(e.data.contract_version)} · remote descriptor code is never loaded.</p><pre>${esc(JSON.stringify(info.generic_view,null,2))}</pre></div>`);}}
  return heading('Compatibility','Extensions','Declarative contracts describe source, renderer, channel and verifier capabilities without granting execution authority.',button('Register contract','new-extension'))+
  `<div class="callout"><strong>This is not a package host</strong>Distribution, approval, isolation and executable package admission remain Platform/Driver Host responsibilities. Launchwright stores bounded metadata and compatibility locks only.</div>`+
  panel('Registered contracts',xs.length?table(['Extension','Contract','Toolchain lock',''],xs.map(e=>`<tr><td>${named(e)}<div class="sub">${esc(e.data.package.name)}@${esc(e.data.package.version)}</div></td><td>${esc(e.data.type)} · ${esc(e.data.contract_version)}<div class="sub">${esc(e.data.state)}</div></td><td>SDK ${esc(e.data.toolchain_lock.native_sdk)}<div class="sub"><code>${esc(e.data.package.sha256.slice(0,18))}…</code></div></td><td><div class="actions">${button('Inspect','inspect',e.id,'secondary small')}${e.data.state==='ACTIVE'?button('Retire','retire-extension',e.id,'secondary small'):''}</div></td></tr>`)):empty('No extension contract registered.','Register metadata only. No code is downloaded or executed from the descriptor.',button('Register contract','new-extension')))+detail;
}
async function history(){const data=await api.read('events.list',{after:0,limit:128});return heading('Audit trail','History','Committed application mutations. Sequence and request binding survive restarts.')+
  panel('Recent registered events',data.items.length?`<ol class="history">${data.items.toReversed().map(e=>`<li><code>#${e.seq}</code><div><strong>${esc(e.operation)}</strong><p>${esc(e.principal)} · workspace revision ${esc(e.revision)}</p><code class="record-id">${esc(e.payload.request_key)}</code></div><time datetime="${esc(e.occurred)}">${time(e.occurred)}</time></li>`).join('')}</ol>`:empty('No committed mutations yet.','Read-only navigation and preparation do not create audit entries.'))+`<p class="small-note">Showing ${data.items.length} entries from sequence 1. ${data.complete?'Complete at watermark '+data.watermark:'More entries exist; the public API supports cursor pagination.'}</p>`;
}
// Accessible schema-driven forms; complex scenario structures are explicit JSON, never executable code.
const selectField=(key,label,items,value)=>({key,label,type:'select',items:items.map(e=>typeof e==='string'?{value:e,label:e}:{value:e.id,label:e.data.name}),value});
const jsonField=(key,label,value,help='JSON only; no executable expressions.')=>({key,label,type:'json',value,help});
const textField=(key,label,value='',type='text',help='')=>({key,label,type,value,help});
const entityFields=(kind,data={})=>{
 const r=get(releaseId),ts=inRelease('target'),sources=inProduct('source'),builds=inProduct('build'),features=inRelease('feature'),availabilities=inRelease('availability'),claims=inRelease('claim'),deliverables=inRelease('deliverable');
 const fields={
 product:[textField('name','Product name',data.name??''),textField('description','Description',data.description??'','textarea')],
 build:[textField('name','Build snapshot name',data.name??''),textField('artifact_digest','Artifact SHA-256',data.artifact_digest??''),textField('version_label','Commercial version label',data.version_label??''),textField('source_revision','Source revision',data.source_revision??''),textField('observed_at','Observed at (ISO)',data.observed_at??''),textField('notes','Build notes',data.notes??'','textarea')],
 release:[textField('name','Release name',data.name??''),textField('build','Build identity label',data.build??'','text','Keep this distinct from the commercial release name.'),selectField('build_id','Pinned build snapshot',[{id:'',data:{name:'No structured snapshot'}},...builds],data.build_id??''),selectField('status','Editorial status',['draft','active','lts','archived'],data.status??'draft'),textField('notes','Brief',data.notes??'','textarea')],
 source:[textField('name','Source name',data.name??''),selectField('type','Source type',['web','cli','mobile-import','godot','document'],data.type??'web'),textField('locator','Locator',data.locator??'','text','Stored as a description. External origins require an approved purpose before navigation.'),textField('purpose','Approved purpose',data.purpose??'','textarea'),selectField('approval','Source approval',['pending','approved','denied'],data.approval??'pending'),textField('build','Build',data.build??r?.data.build??''),selectField('build_id','Structured build snapshot',[{id:'',data:{name:'No structured snapshot'}},...builds],data.build_id??''),selectField('coverage','Observation coverage',['declared','partial','unknown'],data.coverage??'declared'),textField('observed_at','Observation time (ISO)',data.observed_at??'')],
 target:[textField('name','Target name',data.name??''),textField('ui_locale','UI locale',data.ui_locale??'en-US'),textField('editorial_locale','Copy locale',data.editorial_locale??'en-US'),textField('audio_locale','Audio locale',data.audio_locale??'en-US'),textField('role','Product role',data.role??'viewer'),textField('plan','Product plan',data.plan??'basic'),textField('region','Region',data.region??'global'),jsonField('flags','Feature flags',data.flags??{}),jsonField('viewport','Viewport',data.viewport??{width:1440,height:900,scale_milli:1000},'Scale is an integer in thousandths so request digests stay exact.')],
 feature:[textField('name','Feature name',data.name??''),textField('key','Stable feature key',data.key??''),selectField('status','Declared lifecycle',['active','beta','disabled','deprecated'],data.status??'active'),textField('description','Feature description',data.description??'','textarea')],
 availability:[textField('name','Availability rule',data.name??''),selectField('feature_id','Feature',features,data.feature_id),selectField('target_id','Target',ts,data.target_id),selectField('state','Declared availability',['ga','beta','unavailable','unknown'],data.state??'unknown'),selectField('basis','Basis',['declared','imported','observed'],data.basis??'declared'),textField('valid_from','Valid from (ISO)',data.valid_from??''),textField('valid_until','Valid until (ISO)',data.valid_until??'')],
 anchor:[textField('name','Anchor name',data.name??''),selectField('source_id','Source',sources,data.source_id),selectField('target_id','Target',ts,data.target_id),selectField('strategy','Resolution strategy',['aria','text','testid','cli-match','semantic'],data.strategy??'aria'),textField('value','Anchor value',data.value??''),jsonField('expected_count','Expected unique count',data.expected_count??1,'Exactly 1 is required; ambiguity fails closed.')],
 scenario:[textField('name','Scenario name',data.name??''),selectField('source_id','Source',sources,data.source_id),selectField('target_id','Target',ts,data.target_id),textField('version_label','Scenario version',data.version_label??''),selectField('reset_strategy','Reset strategy',['none','fixture-reset','isolated-context','operator-reset'],data.reset_strategy??'none'),jsonField('effects','Declared effects',data.effects??[],'Declarations only; they do not grant effect authority.'),jsonField('steps','Steps',data.steps??[{action:'assert',anchor:'heading'}]),jsonField('anchors','Legacy inline anchors',data.anchors??[{name:'heading',role:'heading',label:'Example product screen',expected_count:1}]),selectField('readiness','Readiness',['declared','needs-validation'],data.readiness??'needs-validation')],
 claim:[textField('name','Claim label',data.name??''),textField('text','Exact claim meaning',data.text??'','textarea'),selectField('target_id','Target',ts,data.target_id),selectField('category','Category',['feature','availability','price','instruction','editorial'],data.category??'feature'),textField('subject','Subject',data.subject??''),textField('scope','Scope',data.scope??''),textField('owner','Owner',data.owner??''),selectField('availability_id','Availability rule',[{id:'',data:{name:'No availability rule'}},...availabilities],data.availability_id??''),textField('unit','Unit',data.unit??''),textField('currency','Currency',data.currency??''),textField('valid_from','Valid from (ISO)',data.valid_from??''),textField('valid_until','Valid until (ISO)',data.valid_until??''),jsonField('evidence_ids','Evidence IDs',data.evidence_ids??[],'Imported evidence cannot manufacture canonical PASS.')],
 copy_block:[textField('name','Copy block name',data.name??''),selectField('target_id','Target',ts,data.target_id),selectField('claim_id','Claim',claims,data.claim_id),textField('locale','Locale',data.locale??'en-US'),selectField('owner','Copy owner',['human','managed'],data.owner??'human'),textField('content','Copy text',data.content??'','textarea')],
 release_contract:[textField('name','Contract name',data.name??''),jsonField('required_claim_ids','Required claim IDs',data.required_claim_ids??claims.map(c=>c.id)),jsonField('optional_claim_ids','Optional claim IDs',data.optional_claim_ids??[]),jsonField('required_deliverable_ids','Required deliverable IDs',data.required_deliverable_ids??deliverables.map(d=>d.id))],
 deliverable:[textField('name','Document name',data.name??''),selectField('target_id','Target',ts,data.target_id),selectField('format','Output format',['markdown','html','json','email','vtt'],data.format??'markdown'),textField('content','Content',data.content??'','textarea'),jsonField('claim_ids','Claim IDs',data.claim_ids??[]),jsonField('copy_block_ids','CopyBlock IDs',data.copy_block_ids??[],'Link copy to structured claims so meaning changes invalidate outputs.'),jsonField('source_ids','Source IDs',data.source_ids??[]),jsonField('captions','Caption cues (VTT only)',data.captions??[],'Objects: start_ms, end_ms, text. Non-overlapping times; media alignment is unverified.')],
 binding:[textField('name','Surface name',data.name??''),selectField('mode','Binding policy',['rolling','pinned','lts'],data.mode??'rolling'),selectField('deliverable_id','Deliverable',inRelease('deliverable'),data.deliverable_id),selectField('pinned_artifact_id','Pinned artifact (required for LTS / pinned)',[{id:'',data:{name:'No fixed artifact'}},...inRelease('artifact')],data.pinned_artifact_id??'')],
 template:[textField('name','Template name',data.name??''),selectField('format','Format',['markdown','html','json','email'],data.format??'markdown'),textField('content','Template text',data.content??'# {{title}}\n\n{{summary}}','textarea'),jsonField('parameters','Allowed parameter names',data.parameters??['title','summary'])],
 glossary:[textField('name','Glossary name',data.name??''),textField('source_locale','Source locale',data.source_locale??'en-US'),textField('target_locale','Target locale',data.target_locale??'es-MX'),jsonField('terms','Reviewed terms',data.terms??[{source:'Example',target:'Ejemplo'}],'Term objects contain source, target and optional case_sensitive.'),selectField('fallback_policy','Fallback policy',['block','manual-only','source-with-warning'],data.fallback_policy??'block'),textField('reviewed_at','Reviewed at (ISO)',data.reviewed_at??new Date().toISOString())],
 font_profile:[textField('name','Font policy name',data.name??''),textField('profile_version','Profile version',data.profile_version??new Date().toISOString().slice(0,10)),jsonField('locales','Covered locales',data.locales??['es-MX']),textField('font_family_ref','Font family reference',data.font_family_ref??'system-ui','text','Reference only. Font binaries are not copied into Launchwright.'),selectField('coverage','Coverage',['declared','subset-known','unknown'],data.coverage??'declared'),selectField('rights','Rights',['owned','licensed','unknown','restricted'],data.rights??'unknown'),textField('license_ref','License / rights reference',data.license_ref??''),{key:'asset_included',label:'Embed font binary (forbidden by this profile)',type:'checkbox',value:false,help:'Keep this off. Launchwright records font policy and rights but does not redistribute font binaries.'},textField('reviewed_at','Reviewed at (ISO)',data.reviewed_at??new Date().toISOString())],
 channel_profile:[textField('name','Profile name',data.name??''),textField('profile_version','Profile version',data.profile_version??new Date().toISOString().slice(0,10)),selectField('channel','Channel',['private-bundle','static-site','docs-repo','review-portal','email-draft','social-draft','app-store-package','play-store-package','cms'],data.channel??'private-bundle'),selectField('delivery_mode','Delivery mode',['export','upload','publish'],data.delivery_mode??'export'),jsonField('formats','Accepted formats',data.formats??['markdown','html']),jsonField('locales','Locales',data.locales??['en-US']),jsonField('max_artifact_bytes','Maximum artifact bytes',data.max_artifact_bytes??8388608),selectField('idempotency','Retry semantics',['native','reconcile','none'],data.idempotency??'reconcile'),selectField('withdrawal','Withdrawal',['supported','corrective-only','unknown'],data.withdrawal??'unknown'),textField('provenance','Profile provenance',data.provenance??'Operator-owned channel profile; external acceptance is not inferred.','textarea'),textField('reviewed_at','Reviewed at (ISO)',data.reviewed_at??new Date().toISOString())]
 };return fields[kind];
};
function openForm(title,fields,onSubmit,submit='Save'){
 const dialog=$('#editor');$('#editor-title').textContent=title;$('#save-editor').textContent=submit;$('#form-error').textContent='';
 $('#editor-fields').innerHTML=fields.map(f=>`<div class="field"><label for="f-${f.key}">${esc(f.label)}</label>${f.type==='select'?`<select id="f-${f.key}" name="${f.key}">${f.items.map(i=>`<option value="${esc(i.value)}"${String(f.value??'')===String(i.value)?' selected':''}>${esc(i.label)}</option>`).join('')}</select>`:f.type==='checkbox'?`<input id="f-${f.key}" name="${f.key}" type="checkbox"${f.value?' checked':''}>`:f.type==='textarea'||f.type==='json'?`<textarea id="f-${f.key}" name="${f.key}" rows="${f.type==='json'?5:8}">${esc(f.type==='json'?JSON.stringify(f.value,null,2):f.value)}</textarea>`:`<input id="f-${f.key}" name="${f.key}" type="${f.type==='password'?'password':'text'}" value="${esc(f.value)}" autocomplete="off">`}${f.help?`<small>${esc(f.help)}</small>`:''}</div>`).join('');
 $('#editor-form').onsubmit=async event=>{event.preventDefault();const save=$('#save-editor');save.disabled=true;$('#form-error').textContent='';try{const data={};for(const f of fields){const el=$(`#f-${f.key}`);data[f.key]=f.type==='json'?JSON.parse(el.value):f.type==='checkbox'?el.checked:el.value;}await onSubmit(data);dialog.close();await render();notice('Saved to the application journal.');}catch(err){$('#form-error').textContent=err.message;}finally{save.disabled=false;}};
 dialog.showModal();
}
$('#close-editor').onclick=$('#cancel-editor').onclick=()=>$('#editor').close();
function editEntity(kind,e){
 if(!['product','build','release','source','feature','release_contract','template','channel_profile','glossary','font_profile'].includes(kind)&&!inRelease('target').length&&kind!=='target'){notice('Add a target context first.');return;}
 openForm(e?`Edit ${kind}`:`Create ${kind}`,entityFields(kind,e?.data),async data=>{
   if(['build','release','source','template','channel_profile','glossary','font_profile'].includes(kind))data.product_id=e?.data.product_id??productId;
   if(['target','feature','availability','anchor','scenario','claim','copy_block','release_contract','deliverable','binding'].includes(kind))data.release_id=e?.data.release_id??releaseId;
   for(const key of ['build_id','availability_id','pinned_artifact_id','valid_from','valid_until','observed_at','purpose'])if(data[key]==='')delete data[key];
   if(kind==='binding'&&!data.pinned_artifact_id)delete data.pinned_artifact_id;
   const result=await mutate(e?'entity.update':'entity.create',e?{id:e.id,expected:e.version,data}:{kind,data});
   if(kind==='product'){productId=result.entity.id;releaseId=null;}if(kind==='release')releaseId=result.entity.id;
   localStorage.setItem('launchwright.product',productId??'');localStorage.setItem('launchwright.release',releaseId??'');
 });
}
root.addEventListener('change',async event=>{try{if(event.target.id==='product-select'){productId=event.target.value;releaseId=null;await refresh();render();}if(event.target.id==='release-select'){releaseId=event.target.value;localStorage.setItem('launchwright.release',releaseId);selected=null;render();}}catch(err){notice(err.message);}});
root.addEventListener('click',async event=>{
 const el=event.target.closest('[data-action]');if(!el)return;const action=el.dataset.action,id=el.dataset.id;
 try{
  if(action.startsWith('navigate-')){location.hash=action.slice(9);return;}
  if(action==='menu'){$('#sidebar').classList.toggle('mobile-open');return;}
  if(action==='theme'){setTheme(document.documentElement.dataset.theme==='dark'?'light':'dark');return;}
  if(action==='refresh'){await refresh();await render();return;}
  if(action==='plan-impact'){
   const data=await api.read('release.impact',{release_id:releaseId});const causeIds=[...new Set(data.items.flatMap(i=>i.changed.map(c=>c.id)))];
   openForm('Save impact proposal',[jsonField('cause_ids','Cause resource IDs',causeIds,'A proposal records causes and scope but creates no jobs or authority.'),textField('note','Planning note','','textarea')],async d=>mutate('impact.plan',{release_id:releaseId,...d}),'Save proposal');return;
  }
  if(action==='recover'){const p=JSON.parse(localStorage.getItem(id));const r=await api.recover(p);if(r.state==='recorded'){await pendingStore.clear(p.args.request.key);await refresh();await render();notice('The original committed result was recovered.');}else notice(`Recovery state: ${r.state}. The original intent remains saved and was not resent.`);return;}
  if(action==='edit'){const e=get(id);editEntity(e.kind,e);return;}
  if(action==='new-document'){
   const targets=inRelease('target');if(!targets.length){notice('Add a target context first.');return;}
   const first=targets[0];
   openForm('Create structured document',[
    textField('name','Document name','Release guide'),selectField('target_id','Target',targets,first.id),textField('locale','Document locale',first.data.editorial_locale),
    selectField('branch_mode','Branch policy',['rolling','pinned','lts'],'rolling'),selectField('format','Render format',['markdown','html'],'markdown'),
    textField('human_title','Human section title','Editorial notes'),textField('human_content','Human-owned content','','textarea','Managed proposals can never overwrite this block.'),
    textField('managed_title','Managed section title','Release steps'),textField('managed_content','Managed starting content','','textarea','Changes to this block are proposed against an exact document revision.'),
    selectField('external_system','External docs base',['local','git','docs-repo'],'local'),textField('external_locator','External locator',''),textField('external_revision','Expected external revision','','text','Required for Git/docs-repo conflict detection.')
   ],async d=>{
    const input={release_id:releaseId,name:d.name,target_id:d.target_id,locale:d.locale,branch_mode:d.branch_mode,format:d.format,sections:[
      {id:'human_notes',title:d.human_title,owner:'human',blocks:[{id:'human_content',kind:'paragraph',owner:'human',content:d.human_content}]},
      {id:'managed_release',title:d.managed_title,owner:'managed',blocks:[{id:'managed_content',kind:'instruction',owner:'managed',content:d.managed_content}]},
    ]};
    if(d.external_system!=='local'){if(!d.external_locator||!d.external_revision)throw Error('External documents require a locator and exact base revision.');input.external_base={system:d.external_system,locator:d.external_locator,revision:d.external_revision};}
    return mutate('document.create',input);
   },'Create document');return;
  }
  if(action==='edit-document-human'){
   const document=get(id),blocks=document.data.sections.filter(s=>s.owner==='human').flatMap(s=>s.blocks.filter(b=>b.owner==='human').map(b=>({id:b.id,data:{name:b.id+' · '+s.title},content:b.content})));if(!blocks.length){notice('No human-owned block is editable.');return;}const first=blocks[0];
   openForm('Edit human-owned block',[selectField('block_id','Human block',blocks,first.id),textField('content','Human content',first.content,'textarea','This operation never edits a managed or imported block.')],async d=>mutate('document.edit_human',{id:document.id,expected:document.version,block_id:d.block_id,content:d.content}),'Save human edit');return;
  }
  if(action==='propose-document'){
   const document=get(id),blocks=document.data.sections.filter(s=>s.owner==='managed').flatMap(s=>s.blocks.filter(b=>b.owner==='managed').map(b=>({id:b.id,data:{name:b.id+' · '+s.title},content:b.content})));if(!blocks.length){notice('No managed block can receive a proposal.');return;}const first=blocks[0];
   openForm('Propose managed change',[selectField('block_id','Managed block',blocks,first.id),textField('content','Proposed content',first.content,'textarea'),textField('reason','Proposal rationale','','textarea')],async d=>mutate('document.propose',{id:document.id,expected:document.version,changes:[{block_id:d.block_id,content:d.content}],reason:d.reason}),'Create proposal');return;
  }
  if(action==='resolve-proposal'){
   const proposal=get(id),document=get(proposal.data.document_id);if(!document){notice('Proposal document is unavailable.');return;}
   const fields=[selectField('decision','Decision',['approve','request-changes','reject'],'request-changes'),textField('comment','Review comment','','textarea')];
   if(document.data.external_base)fields.push(textField('observed_external_revision','Observed external base revision',document.data.external_base.revision,'text','Apply is blocked if this differs from the proposal base.'));
   openForm('Resolve managed proposal',fields,async d=>{const input={proposal_id:proposal.id,decision:d.decision,expected_document:document.version,comment:d.comment};if(document.data.external_base)input.observed_external_revision=d.observed_external_revision;return mutate('document.resolve',input);},'Record decision');return;
  }
  if(action==='render-document'){el.disabled=true;await mutate('document.render',{id});await render();notice('Rendered a new immutable artifact pinned to this document revision.');return;}
  if(action==='new-translation'){
   const sources=[...inRelease('copy_block'),...inRelease('deliverable'),...inRelease('document')],targets=inRelease('target'),glossaries=inProduct('glossary'),fonts=inProduct('font_profile');
   if(!sources.length||!targets.length||!glossaries.length||!fonts.length){notice('A translation needs a source, target, glossary and font policy first.');return;}
   openForm('Create translation',[textField('name','Translation name','Localized release copy'),selectField('source_id','Source text',sources,sources[0].id),selectField('target_id','Target',targets,targets[0].id),selectField('glossary_id','Glossary',glossaries,glossaries[0].id),selectField('font_profile_id','Font policy',fonts,fonts[0].id),selectField('origin','Initial origin',['human','machine'],'human'),textField('text','Translated text','','textarea','Numbers, units and negation receive lexical risk checks but still require human semantic judgment.')],async d=>mutate('translation.create',d),'Create translation');return;
  }
  if(action==='edit-translation'){const tr=get(id);openForm('Edit translation as human',[textField('text','Translated text',tr.data.text,'textarea','If a source, glossary, font policy or target changed, rebase the pins first; text is never discarded automatically.')],async d=>mutate('translation.edit_human',{id:tr.id,expected:tr.version,text:d.text}),'Save human edit');return;}
  if(action==='rebase-translation'){const tr=get(id),info=await api.read('translation.inspect',{id:tr.id});if(!info.changed.length&&!info.blocked.length){notice('Translation pins already match their current inputs.');return;}if(info.blocked.length){notice('A required translation input is missing or retired; rebase is blocked.');return;}await mutate('translation.rebase',{id:tr.id,expected:tr.version});await render();notice('Pins rebased to current inputs. Human text was preserved and semantic review reset to pending.');return;}
  if(action==='review-translation'){const tr=get(id);openForm('Review translation',[selectField('decision','Decision',['approve','request-changes'],'request-changes'),textField('comment','Review comment','','textarea'),{key:'risk_acknowledgement',label:'I performed human semantic review of numbers, units and negation where applicable.',type:'checkbox',value:false,help:'Required when lexical risk flags a critical token or negation.'}],async d=>mutate('translation.review',{id:tr.id,expected:tr.version,decision:d.decision,comment:d.comment,...(d.risk_acknowledgement?{risk_acknowledgement:'human-semantic-review'}:{})}),'Record translation review');return;}
  if(action==='render-translation'){el.disabled=true;await mutate('translation.render',{id});await render();notice('Rendered the current human-reviewed translation with exact source, target, glossary and font-policy pins.');return;}
  if(action==='new-extension'){
   openForm('Register declarative extension contract',[
    textField('name','Contract display name','Reviewed extension contract'),selectField('type','Extension type',['source','renderer','channel','verifier'],'renderer'),textField('contract_version','Contract version','1.0.0'),
    textField('package_name','Package name','example-extension'),textField('package_version','Package version','1.0.0'),textField('package_sha256','Reviewed package SHA-256',''),textField('package_license','Package license','MIT'),textField('package_source','Package source reference','https://example.invalid/package'),
    jsonField('permissions','Permissions',['read-artifacts','write-draft'],'Allowed: read-source, read-artifacts, write-draft, channel-effect, verify.'),jsonField('inputs','Inputs',['document']),jsonField('outputs','Outputs',['artifact']),textField('transformation','Declared transformation','Render a reviewed document into a draft artifact.','textarea'),
    jsonField('preconditions','Preconditions',['source-current']),jsonField('evidence','Evidence outputs',['sha256']),jsonField('app_schema_versions','Compatible Launchwright schemas',['launchwright/1']),
    textField('summary','Generic UI summary','Declarative metadata only. No descriptor code is executed.','textarea'),jsonField('properties','Generic properties',[]),jsonField('actions','Generic actions',[]),
    textField('max_input_bytes','Maximum input bytes','1048576'),textField('max_output_bytes','Maximum output bytes','1048576'),textField('timeout_seconds','Timeout seconds','30')
   ],async d=>mutate('extension.register',{name:d.name,type:d.type,contract_version:d.contract_version,package:{name:d.package_name,version:d.package_version,sha256:d.package_sha256,license:d.package_license,source:d.package_source},permissions:d.permissions,inputs:d.inputs,outputs:d.outputs,transformation:d.transformation,preconditions:d.preconditions,evidence:d.evidence,compatibility:{app_schema_versions:d.app_schema_versions,notes:'Registered through Launchwright generic contract UI.'},limits:{max_input_bytes:Number(d.max_input_bytes),max_output_bytes:Number(d.max_output_bytes),timeout_seconds:Number(d.timeout_seconds)},descriptor:{summary:d.summary,properties:d.properties,actions:d.actions}}),'Register metadata');return;
  }
  if(action==='retire-extension'){const ext=get(id);openForm('Retire extension contract',[textField('reason','Retirement reason','','textarea','Historical records and prepared work remain visible; new use is blocked.')],async d=>mutate('extension.retire',{id:ext.id,expected:ext.version,reason:d.reason}),'Retire contract');return;}
  if(action.startsWith('new-')&&!['new-evidence','new-work','new-document','new-translation','new-extension'].includes(action)){const kind=action.slice(4);if(kind==='release'&&!productId){notice('Create a product first.');return;}editEntity(kind);return;}
  if(action==='render'){el.disabled=true;await mutate('deliverable.render',{id});await render();notice('Created immutable text artifact and source pins.');return;}
  if(action==='preview'||action==='inspect'){selected=id;await render();return;}
  if(action==='new-evidence'){
   openForm('Import provenance declaration',[textField('name','Evidence name'),selectField('target_id','Target',inRelease('target')),selectField('source_id','Source',inProduct('source')),textField('build','Observed build',get(releaseId).data.build),selectField('classification','Source classification',['actual','demo','sanitized','editorial','generated','imported'],'imported'),selectField('rights','Rights declaration',['owned','licensed','unknown','restricted'],'unknown'),textField('origin_digest','Original content SHA-256'),textField('description','What was observed and what was not','','textarea')],async d=>mutate('evidence.import',{...d,release_id:releaseId}),'Import as unverified');return;
  }
  if(action==='freeze'){
   openForm('Freeze a release candidate',[textField('name','Candidate name',get(releaseId).data.name+' — review'),jsonField('artifact_ids','Exact artifact IDs',inRelease('artifact').map(a=>a.id),'Remove superseded versions. Every selected artifact must still match its source pins.'),jsonField('channel_profile_ids','Pinned channel profile IDs',inProduct('channel_profile').map(p=>p.id),'Changing a pinned ChannelProfile invalidates the candidate.'),textField('destination','Private alias','release-draft'),jsonField('contract','Review contract',{version:'review-v2',required_reviewers:1,require_claims_verified:true,required_dimensions:['technical','editorial','permissions']})],async d=>mutate('candidate.freeze',{...d,release_id:releaseId}),'Freeze exact candidate');return;
  }
  if(action==='review-decision'){const c=get(id);openForm('Review decision',[selectField('dimension','Review dimension',['technical','editorial','permissions'],'editorial'),selectField('decision','Decision',['approve','request-changes','reject'],'request-changes'),textField('comment','Reason or requested change','','textarea'),textField('waiver_reason','Optional waiver reason','','textarea','A waiver remains visible and never turns technical FAIL/UNKNOWN into PASS.'),textField('waiver_valid_until','Optional waiver expiry (ISO)','')],async d=>{const input={id,candidate_sha256:c.data.candidate_sha256,dimension:d.dimension,decision:d.decision,comment:d.comment};if(d.waiver_reason)input.waiver={reason:d.waiver_reason,...(d.waiver_valid_until?{valid_until:d.waiver_valid_until}:{})};return mutate('candidate.review',input);},'Record decision');return;}
  if(action==='export-bundle'){const c=get(id);const result=await mutate('candidate.export_bundle',{id,candidate_sha256:c.data.candidate_sha256});await render();notice('Exact deterministic ZIP exported locally; no external delivery was recorded.');selected=c.id;return;}
  if(action==='download-bundle'){location.href='/api/v1/bundles/'+encodeURIComponent(id)+'/download';return;}
  if(action==='prepare-channel'){
   const candidates=inRelease('candidate'),profiles=inProduct('channel_profile').filter(p=>p.data.delivery_mode!=='export');if(!candidates.length||!profiles.length){notice('Freeze a candidate with a non-export ChannelProfile first.');return;}
   openForm('Prepare channel delivery',[selectField('candidate_id','Frozen candidate',candidates,candidates.at(-1).id),selectField('channel_profile_id','Pinned ChannelProfile',profiles,profiles[0].id),textField('logical_key','Logical request key','release:'+Date.now(),'text','Retries reuse the same logical key and must reconcile the prior attempt first.'),{key:'authorization',label:'I authorize preparation of this external channel delivery intent. No browser-side send occurs.',type:'checkbox',value:false}],async d=>{if(!d.authorization)throw Error('Explicit authorization is required.');const c=get(d.candidate_id);return mutate('channel.prepare',{candidate_id:c.id,candidate_sha256:c.data.candidate_sha256,channel_profile_id:d.channel_profile_id,logical_key:d.logical_key,authorization:'explicit-channel-delivery'});},'Prepare exact attempt');return;
  }
  if(action==='inspect-channel'){selected=id;await render();return;}
  if(action==='reconcile-channel'){const a=get(id);openForm('Record destination reconciliation',[selectField('state','Observed destination state',['published','processing','failed','not_found','unknown'],'unknown'),textField('source','Observation source','operator-manual-check','text','Name the independently inspected source; this does not become technical product evidence.'),textField('checked_at','Checked at (ISO)',new Date().toISOString()),textField('fingerprint','Observed fingerprint','','text','Required when state is published.'),textField('external_id','External resource ID','')],async d=>{const observation={state:d.state,source:d.source,checked_at:d.checked_at};if(d.fingerprint)observation.fingerprint=d.fingerprint;if(d.external_id)observation.external_id=d.external_id;return mutate('channel.reconcile',{id:a.id,pending_digest:a.data.pending_digest,observation});},'Record observation');return;}
  if(action==='retry-channel'){const a=get(id);openForm('Prepare explicit retry',[textField('logical_key','Logical request key',a.data.logical_key),{key:'authorization',label:'I understand the prior attempt was reconciled as not found; prepare one explicit retry. No automatic resend occurs.',type:'checkbox',value:false}],async d=>{if(!d.authorization)throw Error('Explicit retry authorization is required.');const c=get(a.data.candidate_id);return mutate('channel.prepare',{candidate_id:c.id,candidate_sha256:c.data.candidate_sha256,channel_profile_id:a.data.channel_profile_id,logical_key:d.logical_key,authorization:'explicit-channel-delivery',retry_of:a.id});},'Prepare retry');return;}
  if(action==='withdraw-channel'){const a=get(id);openForm('Plan withdrawal',[selectField('scope','Withdrawal scope',['destination-resource','published-version','known-owned-copies'],'published-version'),textField('reason','Reason','','textarea'),selectField('replacement_candidate_id','Optional replacement',[{id:'',data:{name:'No replacement'}},...inRelease('candidate')],'')],async d=>{const input={id:a.id,scope:d.scope,reason:d.reason};if(d.replacement_candidate_id)input.replacement_candidate_id=d.replacement_candidate_id;return mutate('channel.withdraw_plan',input);},'Save plan only');return;}
  if(action==='deliver'){const c=get(id);const prior=inRelease('delivery').filter(d=>d.data.name===c.data.manifest.destination).sort((a,b)=>Number(BigInt(a.data.alias_version.revision)-BigInt(b.data.alias_version.revision))).at(-1);openForm('Record private draft',[textField('destination','Destination (read-only binding)',c.data.manifest.destination),{key:'acknowledge_draft',label:'I understand: this records a private draft, not a verified or external publication.',type:'checkbox',value:false}],async d=>{if(d.destination!==c.data.manifest.destination)throw Error('Destination is frozen in the candidate.');return mutate('candidate.deliver_private',{id,candidate_sha256:c.data.candidate_sha256,alias_expected:prior?.data.alias_version??null,acknowledge_draft:d.acknowledge_draft});},'Record private draft');return;}
  if(action==='instantiate'){const t=get(id);openForm('Instantiate template',[textField('name','Deliverable name',t.data.name),selectField('target_id','Target',inRelease('target')),jsonField('parameters','Parameter values',Object.fromEntries(t.data.parameters.map(p=>[p,''])))],async d=>mutate('template.instantiate',{...d,id,release_id:releaseId}),'Create deliverable');return;}
  if(action==='new-work'){openForm('Prepare a Platform intent',[textField('name','Intent label'),selectField('action','Canonical action',['recipes.prepare','recipes.execute','jobs.get','graph.observe','graph.observation','evidence.get','artifacts.get'],'recipes.prepare'),jsonField('arguments','Canonical action input',{},'Use the actual negotiated Platform action schema. No new endpoint is inferred.'),jsonField('budget','Budget proposal',{max_cost_microunits:0,currency:'USD',max_runtime_seconds:60})],async d=>mutate('work.prepare',{...d,release_id:releaseId}),'Save intent only');return;}
 }catch(err){notice(err.message);await render();}finally{el.disabled=false;}
});
function login(error=''){
 root.innerHTML=`<main class="login" id="main"><div class="brand"><span class="brand-mark" aria-hidden="true">L</span>Launchwright</div><div class="eyebrow">Local release workspace</div><h1>Your launch.<br>Your source of truth.</h1><p>Unlock the workspace running on this computer. No account is created and no data is published.</p><form id="login-form"><label for="token">Local session token</label><input id="token" name="token" type="password" autocomplete="off" required><button type="submit">Open workspace</button><p id="login-error" role="alert">${esc(error)}</p></form><p class="small-note">The launcher prints the token file path. Open it locally; never put the token in a URL, source file or release package.</p><p class="small-note">AGPL-3.0-only · <a href="/LICENSE">License</a></p></main>`;
 $('#login-form').onsubmit=async e=>{e.preventDefault();try{await api.request('/api/v1/session',{token:$('#token').value});$('#token').value='';await refresh();route();}catch(err){$('#login-error').textContent=err.message;}};
}
try{await refresh();route();}catch(err){login(err.code==='PermissionDenied'?'':err.message);}
